############ DO NOT CHANGE THESE #################
SUPPORTED:=./uart:./pwm:./bootrom:./clint:./common_bsv:./fabrics/axi4:./fabrics/axi4lite:./bram:./gpio:./sdram:./jtagdtm:./onfi:./plic:./i2c:./qspi:./riscvDebug013
TOP_MODULE:=mkdummy

############# User changes to be done below #################
TOP_DIR:= jtagdtm
TOP_FILE:= dmi_tap.bsv

