#!/usr/bin/env python3
"""
extract_otbn_binary.py — Extract OTBN ELF binary and emit C + header files.

Usage:
    python3 extract_otbn_binary.py <app_name> <input.elf> <out_dir>

Outputs:
    <out_dir>/<app_name>_app.c      — IMEM array + DMEM .data array (_local_ symbols)
    <out_dir>/<app_name>_defs.h     — compile-time #defines for ALL remote DMEM addresses

How it works on RV64 (Shakti vs OpenTitan RV32):
  OpenTitan uses a pointer-cast trick: symbol's LINKER ADDRESS encodes the DMEM offset.
  That works on RV32 (pointers fit in uint32_t) but fails on RV64 in static initializers.

  Shakti approach: generate a header with #define _OTBN_REM_<app>_<sym> <value>u.
  otbn.h OTBN_SYMBOL_ADDR expands to _OTBN_REM_<app>_<sym>, so OTBN_ADDR_T_INIT
  resolves to a compile-time integer constant — no pointer casts needed.

  Compile with: -include gen/<app_name>_defs.h

CRC32 checksum format (matches OpenTitan otbn_build.py):
  For each 32-bit word W at OTBN word-offset I:
    CRC update over W_bytes[0..3] then location_bytes[0..1]
    location = (is_imem << 15) | I  (LE 16-bit)
"""

import sys
import struct
import binascii
from pathlib import Path


def compute_checksum(imem_words, dmem_words, dmem_start_word_offset):
    checksum = 0
    for i, w in enumerate(imem_words):
        checksum = binascii.crc32(struct.pack('<I', w), checksum)
        location = (1 << 15) | i
        checksum = binascii.crc32(struct.pack('<H', location), checksum)
    for i, w in enumerate(dmem_words):
        checksum = binascii.crc32(struct.pack('<I', w), checksum)
        location = (dmem_start_word_offset + i) & 0x7FFF
        checksum = binascii.crc32(struct.pack('<H', location), checksum)
    return checksum & 0xFFFFFFFF


def extract_section_words(elf_file, section_name):
    section = elf_file.get_section_by_name(section_name)
    if section is None:
        return [], 0
    data = section.data()
    if len(data) % 4:
        data += b'\x00' * (4 - len(data) % 4)
    words = list(struct.unpack_from(f'<{len(data)//4}I', data))
    return words, section['sh_addr']


def get_all_symbols(elf_file):
    """Return dict of {name: value} for all global symbols in the ELF."""
    symtab = elf_file.get_section_by_name('.symtab')
    if symtab is None:
        return {}
    result = {}
    for sym in symtab.iter_symbols():
        if sym.name:
            result[sym.name] = sym['st_value']
    return result


def write_c_file(app_name, imem_words, dmem_words, out_path):
    """C file with IMEM and DMEM .data arrays (_local_ symbols)."""
    local = f'_otbn_local_app_{app_name}_'
    lines = [
        '// AUTO-GENERATED by extract_otbn_binary.py — DO NOT EDIT.',
        f'// OTBN application: {app_name}',
        '#include <stdint.h>',
        '',
        f'// ---- IMEM: {len(imem_words)} words ({len(imem_words)*4} bytes) ----',
    ]

    # Each array gets its own linker section so the ordering and boundary
    # symbols are correct regardless of GCC's -Os data-reordering.
    # The linker script (shakti.ld) must list these sections in this order:
    #   .rodata.otbn.*.imem_data  then  .rodata.otbn.*.imem_end
    #   .rodata.otbn.*.dmem_data  then  .rodata.otbn.*.dmem_end
    imem_sec   = f'.rodata.otbn.{app_name}.imem_data'
    imem_e_sec = f'.rodata.otbn.{app_name}.imem_end'
    dmem_sec   = f'.rodata.otbn.{app_name}.dmem_data'
    dmem_e_sec = f'.rodata.otbn.{app_name}.dmem_end'

    attr_imem   = f'__attribute__((section("{imem_sec}"), used))'
    attr_imem_e = f'__attribute__((section("{imem_e_sec}"), used, aligned(4)))'
    attr_dmem   = f'__attribute__((section("{dmem_sec}"), used))'
    attr_dmem_e = f'__attribute__((section("{dmem_e_sec}"), used, aligned(4)))'

    lines.append(f'{attr_imem}')
    lines.append(f'const uint32_t {local}_imem_start[] = {{')
    for i, w in enumerate(imem_words):
        comma = ',' if i < len(imem_words) - 1 else ''
        lines.append(f'  0x{w:08x}u{comma}')
    lines.append('};')
    lines.append(f'// _imem_end address = &_imem_start[N] because linker places')
    lines.append(f'// .rodata.otbn.*.imem_end immediately after .rodata.otbn.*.imem_data')
    lines.append(f'{attr_imem_e}')
    lines.append(f'const uint32_t {local}_imem_end[1] = {{0}};')
    lines.append('')

    lines.append(f'// ---- DMEM .data: {len(dmem_words)} words ({len(dmem_words)*4} bytes) ----')
    if dmem_words:
        lines.append(f'{attr_dmem}')
        lines.append(f'const uint32_t {local}_dmem_data_start[] = {{')
        for i, w in enumerate(dmem_words):
            comma = ',' if i < len(dmem_words) - 1 else ''
            lines.append(f'  0x{w:08x}u{comma}')
        lines.append('};')
    else:
        lines.append(f'{attr_dmem}')
        lines.append(f'const uint32_t {local}_dmem_data_start[1] = {{0}};')
    lines.append(f'{attr_dmem_e}')
    lines.append(f'const uint32_t {local}_dmem_data_end[1] = {{0}};')

    out_path.write_text('\n'.join(lines) + '\n')
    print(f'[C]   {out_path}  ({len(imem_words)} IMEM words, {len(dmem_words)} DMEM words)')


def write_defs_header(app_name, all_syms, dmem_data_start_addr, checksum, out_path):
    """Header with #define for every OTBN symbol (DMEM addresses + checksum).

    OTBN_SYMBOL_ADDR(app, sym) expands to _OTBN_REM_<app>_<sym>.
    These #defines make OTBN_ADDR_T_INIT resolve to a compile-time constant.
    """
    prefix = f'_OTBN_REM_{app_name}_'
    lines = [
        '// AUTO-GENERATED by extract_otbn_binary.py — DO NOT EDIT.',
        f'// Remote (OTBN-side) DMEM addresses for app: {app_name}',
        f'// Include via: -include gen/{app_name}_defs.h',
        '',
        '#ifndef SHAKTI_P384_OTBN_DEFS_H_',
        '#define SHAKTI_P384_OTBN_DEFS_H_',
        '',
        f'// Synthesized symbols (not in ELF .symtab)',
        f'#define {prefix}_dmem_data_start  0x{dmem_data_start_addr:08x}u',
        f'#define {prefix}_checksum         0x{checksum:08x}u',
        '',
        '// DMEM variable addresses (from OTBN ELF .symtab)',
    ]

    # Emit all symbols from the ELF symbol table
    # Skip: private symbols (_prefix), file-path debug symbols (contain '/'),
    # and section-type symbols that aren't valid C identifiers.
    for sym_name, value in sorted(all_syms.items()):
        if not sym_name or sym_name.startswith('_') or '/' in sym_name or '.' in sym_name:
            continue
        define_name = f'{prefix}{sym_name}'
        lines.append(f'#define {define_name}  0x{value:08x}u')

    lines += ['', '#endif  // SHAKTI_P384_OTBN_DEFS_H_']
    out_path.write_text('\n'.join(lines) + '\n')
    print(f'[HDR] {out_path}  ({len(all_syms)} symbols + 2 synthesized)')


def main():
    if len(sys.argv) != 4:
        print(f'Usage: {sys.argv[0]} <app_name> <input.elf> <out_dir>', file=sys.stderr)
        sys.exit(1)

    app_name = sys.argv[1]
    elf_path = Path(sys.argv[2])
    out_dir  = Path(sys.argv[3])
    out_dir.mkdir(parents=True, exist_ok=True)

    try:
        from elftools.elf.elffile import ELFFile
    except ImportError:
        print('Error: pyelftools not installed.\n  pip3 install pyelftools', file=sys.stderr)
        sys.exit(1)

    with open(elf_path, 'rb') as f:
        elf = ELFFile(f)
        imem_words, _ = extract_section_words(elf, '.text')
        dmem_words, _ = extract_section_words(elf, '.data')
        all_syms      = get_all_symbols(elf)

        dmem_data_start_addr = all_syms.get('_dmem_data_start')
        if dmem_data_start_addr is None:
            sec = elf.get_section_by_name('.data')
            dmem_data_start_addr = sec['sh_addr'] if sec else 0
            print(f'Warning: _dmem_data_start not found, using .data sh_addr = '
                  f'0x{dmem_data_start_addr:x}')

        checksum = compute_checksum(imem_words, dmem_words, dmem_data_start_addr // 4)

    write_c_file(app_name, imem_words, dmem_words,
                 out_dir / f'{app_name}_app.c')
    write_defs_header(app_name, all_syms, dmem_data_start_addr, checksum,
                      out_dir / f'{app_name}_defs.h')

    print(f'\nDone. Next steps:')
    print(f'  cd /home/soham/shakti/p384')
    print(f'  make')


if __name__ == '__main__':
    main()
