//see LICENSE.iitm for license details
/*

Author : Sadhana S
Email id : sadhashan118@gmail.com
*/
/*doc:overview:
SPI is a synchronous serial I/O port that allows a serial bit stream of programmed length to be shifted into and out of the device at programmable bit transfer rate. 

Configurations
^^^^^^^^^^^^^^
The output enables of NCS and SCLK decides whether they are generated by the SPI controller or received from the device connected to the controller.
Four possible communication modes - Only Transmit, only receive, transmit and immediate receive and simultaneous transmit and receive.
LSB/MSB first based on the slave configuration.
The length of the bit stream to be transferred or received can be programmed through the rg_total_bit_tx and rg_total_bit_rx bits in rg_comm_ctrl register. 

Delayed transmit control is achieved by providing required delay through rg_cs_t_delay bits in rg_clk_ctrl register and also the hold time for the slave can be through rg_t_cs_delay bits in rg_clk_ctrl register.
Supports all the four SPI clock modes.
The required bit transfer rate is achieved by giving appropriate value to rg_prescaller bits in rg_clk_ctrl register. 


32-level receive and transmit FIFO is provided to reduce servicing overhead. 
32-bit memory mapped tx and rx registers are used to enqueue and dequeue data to and from FIFO respectively. 

Following communcation statuses are available - busy, transmit enable, receive not enable, FIFO thresholds and overrun.

FIFO statuses like, empty, quad, half and full levels are provided in fifo status register and interrupts can also be generated for these events.

Each SPI module has four external IO pins - Master in/Slave out(MISO) pin, Master out/Slave in(MOSI) pin, Synchronous clock(SCLK) and  Chip Select(CS) pin. 
All the pins of the Standard SPI module have input qualification control and the input qualification cycle is configured through rg_qual_cycles register. 
To enable input qualification control, enable the define IQC in simulation.

Sequence of execution
^^^^^^^^^^^^^^^^^^^^^

To transmit, 
	1. write into tx data register (if the data to be transmitted is more than 32 bits, write multiple times into the tx data register, every write will push its contents to the TX FIFO
	2. Write into clock control register, interrupt enable register and input qualification register
	3. Now enable the SPI transaction through communication control register

To receive,
	1. Write into clock register, interrupt enable register and input qualification register
	2. And now enable the SPI transaction through communication control register
	3. The received data will be available in RX data register(If data to be received is more than 32 bits, perform multiple 
	read RX data register, this will pop the contents from RX FIFO)


SPI state changes
^^^^^^^^^^^^^^^^^

Master mode
^^^^^^^^^^^

As soon as spi_en is given to rg_commctrl register, following happens sequentially
	1. After one cycle, ncs goes low
	2. In the next cycle, sclk counter starts and upcounts till prescale value. The sclk value inverts or remains the same depending on the clk_phase and clk_polarity set in the clock control register. This sclk generation happens throughout the SPI transaction.
	3. If any setup delay set in clock control register, sclk is not sent as output, til the setup delay is met. If there is no setup delay, sclk will be sent as output immediately (in the next cycle) after ncs goes low
	4. Once the setup delay is met, transmit from the controller happens when sclk counter is zero and that value is held till the counter reaches the prescale value. The controller reads an input value when sclk counter is equal to half the prescale value.
	5. Only transmit, only receive, receive immediately after transmit or simultaneously transmit and receive happens based on the communication mode set in the communication control register.
	6. The transmit and recive continues till the number of bits to be transmitted or the number of bits to be received is done according to the configuration in communication control register.
	7. Once the transmit - receive is done, the sclk stops but ncs will go high only after hold delay is met according to the configuration in clock control register. This completes the SPI transaction and spi en also will be reset to zero. To start the next transaction configure the memory map registers accordingly

Slave mode
^^^^^^^^^^
Slave mode is similar to the master mode except, ncs and sclk will be received from the SPI device connected to the controller.
The spi en is expected to be set before the ncs goes low and once the ncs goes low, the SPI state changes happens as above.
In slave mode, sclk counter will not be used instead the rising or falling edge is detected and transmit and receive edge is computed.
Once the ncs goes high, spi en is reset by the controller.

Rule firing order
^^^^^^^^^^^^^^^^^
rl_chip_select_control_master_mode/rl_chip_select_control_slave_mode always fires.

rl_spi_clock_generator_master_mode/rl_spi_clock_generator_slave_mode fires when rg_ncs is reset.

rl_mi_qualification/rl_mi_qualification fires if rg_receive state is in DATA_RECEIVE state.

rl_tx_fifo_threshold_updates and rl_rx_fifo_threshold_updates always fires

rl_transfer_data_from_txreg_to_txfifo fires when rg_tx_data is written 

rl_transfer_data_from_rxfifo_to_rxreg fires when rg_rx_ddata is read and receive operation is done.


Only Transmit
^^^^^^^^^^^^^
(rl_set_up_time)*set_up_delay -> rl_transmit_idle_to_data_transfer -> (rl_transmit_state)*rg_total_bit_tx -> (rl_abort_condition)*hold_delay


Only Receive
^^^^^^^^^^^^
(rl_set_up_time)*set_up_delay -> rl_receive_idle_to_data_receive -> (rl_receive_state)*rg_total_bit_rx ->  (rl_abort_condition)*hold_delay


Transmit and Immediate Receive
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(rl_set_up_time)*set_up_delay -> rl_transmit_idle_to_data_transfer -> (rl_transmit_state)*rg_total_bit_tx -> rl_receive_idle_to_data_receive -> (rl_receive_state)*rg_total_bit_rx ->  (rl_abort_condition)*hold_delay


Transmit and Receive
^^^^^^^^^^^^^^^^^^^^
(rl_set_up_time)*set_up_delay -> rl_transmit_idle_to_data_transfer and rl_receive_idle_to_data_receive -> (rl_transmit_state)*rg_total_bit_tx and (rl_receive_state)*rg_total_bit_rx -> (rl_abort_condition)*hold_delay


*/
package sspi;

import ConcatReg ::*;
import Semi_FIFOF        :: *;
import FIFOLevel::*;
import AXI4_Lite_Types   :: *;
import AXI4_Lite_Fabric  :: *;
import AXI4_Types::*;
import AXI4_Fabric::*;
import FIFOF::*;
import Clocks::*;
import SpecialFIFOs::*;
import ConfigReg ::*;
import FIFO::*;
import Vector::*;
import BUtils::*;
import MIMO_MODIFY::*;
import DefaultValue::*;
`ifdef IQC
	import iqc::*;
`endif
`include "sspi.defines"
`include "Logger.bsv"

`define sclk_delay 3
`define mosi_delay 2
export Ifc_sspi 			(..);
export Ifc_sspi_io 			(..);
export Ifc_sspi_axi4 		(..);
export Ifc_sspi_axi4lite 	(..);
export mksspi_axi4;
export mksspi_axi4lite;
export mk_sspi;

// Enum to define the transmit state transfers
typedef enum{
			 IDLE,
			 START_TRANSMIT,
			 DATA_TRANSMIT,
			 TRANSMIT_DONE
		} Transmit_state deriving(Bits, Eq, FShow);
			 		
// Enum to define the receive state transfers
typedef enum{
			 IDLE,
			 START_RECEIVE,
			 DATA_RECEIVE,
			 RECEIVE_DONE
		} Receive_state deriving(Bits, Eq, FShow);

// Enum to define the SPI Transaction transfers
typedef enum{
			IDLE,
			WAIT,
			SETUP_PHASE,
			ACTIVE,
			HOLD_PHASE
	   } Spi_state deriving(Bits, Eq, FShow);

// sspi_io io interface with all the four inputs, outputs and output enables
// (*always_ready, always_enabled*)
interface Ifc_sspi_io;
		//mosi input output
		method bit mosi_outen;
 		method bit mosi_out;
		method Action mosi_in(bit val);
		//sclk input output
		method bit sclk_outen;
 		method bit sclk_out;
		method Action sclk_in(bit val);
		//miso input output
		method bit miso_outen;
 		method Action miso_in(bit val);
		method bit miso_out;
		//ncs input output
		//Multiple Slave for SPI
		method bit ncs_outen0;
 		method bit ncs_out0;
		method Action ncs_in0(bit val);
		
		method bit ncs_outen1;
 		method bit ncs_out1;
		method Action ncs_in1(bit val);
		
		method bit ncs_outen2;
 		method bit ncs_out2;
		method Action ncs_in2(bit val);
		
		method bit ncs_outen3;
 		method bit ncs_out3;
		method Action ncs_in3(bit val);
		
		
endinterface

// sspi axi interface which has write and read methods to receive write and read requests. It also the above sspi_io interface
// and interrupt connection to PLIC
interface Ifc_sspi#(numeric type addr_width, numeric type data_width);
	/*doc : subifc : SSPI_IO interface which holds all the four input, output and output enables */
	interface Ifc_sspi_io subifc_io;
	/*doc : method : method to receive write requests from AXI */
	method ActionValue#(Bool) mav_write_req(Bit#(addr_width) addr, Bit#(data_width) data, Bit#(2) size);
	/*doc : method : method to receive read requests from AXI */
	method ActionValue#(Tuple2#(Bool, Bit#(data_width))) mav_read_req(Bit#(addr_width) addr, Bit#(2) size);
	/*doc : method : method to send side band interrupt request to PLIC */
	method Bit#(1) mv_sb_sspi_interrupt;
endinterface


/*doc:module: Standard SPI module */
module mk_sspi(Ifc_sspi#(addr_width, data_width))
				provisos(Add#(a__, 32, data_width),
					 Add#(b__,  4, data_width),
					 Mul#(32, c__, data_width),
					 Mul#( 8, d__, data_width),
					 Mul#(16, e__, data_width),
					 Mul#( 4, f__, data_width),
					 Add#(16, g__, data_width)
					);
	Reg#(Bit#(2)) rg_slave_select	<- mkRegA(0); 
	/* doc : reg : holds the MOSI pin's output enable. If set, output is transmitted through this pin else input is read from this pin */
	Reg#(bit) rg_mosi_output_enable <- mkRegA(1);
	/* doc : reg : holds the MISO pin's output enable. If set, output is transmitted through this pin else input is read from this pin */
	Reg#(bit) rg_miso_output_enable <- mkRegA(0);
	/* doc : reg : holds the NCS pin's output enable. If set, the controller generates the ncs else ncs is expected from the spi device */
	Reg#(bit) rg_ncs_output_enable  <- mkRegA(0);
	/* doc : reg : holds the SCLK pin's output enable. If set, the controller generates the sclk else sclk is expected from the spi device */
	Reg#(bit) rg_sclk_output_enable <- mkRegA(1);
	/* doc : reg : holds the total number of bits to be transmitted in a spi transaction */
	Reg#(Bit#(8)) rg_total_bit_rx	<- mkRegA(0);
	/* doc : reg : holds the total number of bits to be received in a spi transaction */
	Reg#(Bit#(8)) rg_total_bit_tx	<- mkRegA(0);
	/* doc : reg : holds the communication mode of the spi transaction. 00 - only transmit; 01 - only receive; 10 - transmit and immediate receive; 11 - transmit and receive */
	Reg#(Bit#(2)) rg_comm_mode		<- mkRegA(0);
	/* doc : reg : holds whether the spi transaction is LSB first. If set LSB first else MSB first */
	Reg#(bit) rg_lsbfirst			<- mkRegA(0);
	/* doc : reg : holds the spi enable control. Once set, spi transaction will start and it will be reset at the end of spi transaction */
	Reg#(bit) rg_spi_en				<- mkRegA(0);
	//unused register
	Reg#(bit) rg_master_mode		<- mkRegA(1);
	//doc : reg : concatenates all the communication control fields described before for AXI read and write to the memory map register
	Reg#(Bit#(32)) rg_comm_ctrl = concatReg13(readOnlyReg(4'd0),rg_slave_select,rg_mosi_output_enable,rg_miso_output_enable,rg_ncs_output_enable,rg_sclk_output_enable,
												rg_total_bit_rx,rg_total_bit_tx,rg_comm_mode,readOnlyReg(1'd0),rg_lsbfirst,rg_spi_en,rg_master_mode);

	/* doc : reg : holds the hold delay */
	Reg#(Bit#(8)) rg_t_cs_delay <- mkRegA(0);
	/* doc : reg : holds the setup delay */
	Reg#(Bit#(8)) rg_cs_t_delay <- mkRegA(0);
	/* doc : reg : holds the prescaller value of the sclk */
	Reg#(Bit#(8)) rg_prescaller <- mkRegA(0);
	/* doc : reg : holds the clock phase */
	Reg#(bit) rg_clk_phase		<- mkRegA(0);
	/* doc : reg : holds the clock polarity */
	Reg#(bit) rg_clk_polarity 	<- mkRegA(0);
	//doc : reg : concatenates all the clock fields described before for AXI read and write to the memory map register
	Reg#(Bit#(32)) rg_clk_ctrl = concatReg6(readOnlyReg(6'd0),rg_t_cs_delay,rg_cs_t_delay,rg_prescaller,rg_clk_phase,rg_clk_polarity);

	/* doc : reg : holds the tx data. This register is written by the AXI write request and once written the data is transferred to TX FIFO */
	Reg#(Bit#(32)) rg_tx_data <- mkRegA(0);
	/* doc : reg : holds the tx data. This register is read by the AXI read request. The data is written from the RX FIFO */
	Reg#(Bit#(32)) rg_rx_data <- mkRegA(0);

	/* doc : reg : overrun interrupt enable bit. Overrun occurs when the received data couldn't be enqueued because RX FIFO is full. This when set, overrun interrupt is sent to PLIC */
	Reg#(bit) rg_rx_over_run_err_intr_en <- mkRegA(0);
	/* doc : reg : RX FIFO full interrupt enable bit. This when set, interrupt is sent to PLIC when RX FIFO is full - 32 entries */
	Reg#(bit) rg_rx_fifo_full_intr_en <- mkRegA(0);
	/* doc : reg : RX FIFO half interrupt enable bit. This when set, interrupt is sent to PLIC when RX FIFO has 16 entries*/
	Reg#(bit) rg_rx_fifo_half_intr_en <- mkRegA(0);
	/* doc : reg : RX FIFO quad interrupt enable bit. This when set, interrupt is sent to PLIC when RX FIFO has 8 entries */
	Reg#(bit) rg_rx_fifo_quad_intr_en <- mkRegA(0);
	/* doc : reg : RX FIFO empty interrupt enable bit. This when set, interrupt is sent to PLIC when RX FIFO is empty */
	Reg#(bit) rg_rx_fifo_empty_intr_en <- mkRegA(0);
	/* doc : reg : TX FIFO full interrupt enable bit. This when set, interrupt is sent to PLCI when TX FIFO is full - 32 entries*/
	Reg#(bit) rg_tx_fifo_full_intr_en <- mkRegA(0);
	/* doc : reg : TX FIFO half interrupt enable bit. This when set, interrupt is sent to PLIC when TX FIFO has 16 entries*/
	Reg#(bit) rg_tx_fifo_half_intr_en <- mkRegA(0);
	/* doc : reg : TX FIFO quad interrupt enable bit. This when set, interrupt is sent to PLIC when TX FIFO has 8 entries */
	Reg#(bit) rg_tx_fifo_quad_intr_en <- mkRegA(0);
	/* doc : reg : TX FIFO empty interrupt enable bit. This when set, interrupt is sent to PLIC when TX FIFO is empty */
	Reg#(bit) rg_tx_fifo_empty_intr_en <- mkRegA(0);
	//doc : reg : concatenates all the interrupt enable bits described before for AXI read and write to the memory map register
	Reg#(Bit#(16)) rg_intr_en = concatReg10(readOnlyReg(7'd0),rg_rx_over_run_err_intr_en,rg_rx_fifo_full_intr_en,rg_rx_fifo_half_intr_en,rg_rx_fifo_quad_intr_en,rg_rx_fifo_empty_intr_en,
											rg_tx_fifo_full_intr_en,rg_tx_fifo_half_intr_en,rg_tx_fifo_quad_intr_en,rg_tx_fifo_empty_intr_en);
		
	Vector#(`sclk_delay, Reg#(Bit#(1)))   val_sclk_delay  <- replicateM(mkReg(0));
	Vector#(`sclk_delay, Reg#(Bit#(1)))   sclkEn_delay    <- replicateM(mkReg(0));
	Vector#(`mosi_delay, Reg#(Bit#(1)))   val_mosi_delay  <- replicateM(mkReg(0));
	Vector#(`mosi_delay, Reg#(Bit#(1)))   mosiEn_delay    <- replicateM(mkReg(0));

	/*doc : reg : Overrun bit. This will be set when there is an overrun during receive operation */
	Reg#(bit) rg_over_run <- mkRegA(0);
	/*doc : reg : RX FIFO Threshold bits to know the number of entries in the RX FIFO. 00 -  */
	Reg#(Bit#(2)) rg_rx_fifo_th <- mkRegA(0);
	/*doc : reg : TX FIFO Threshold bits to know the number of entries in the TX FIFO. 00 - */
	Reg#(Bit#(2)) rg_tx_fifo_th <- mkRegA(0);
	/*doc : reg : Receive not enable bit. This bit will be reset when the receive operation starts and will be set once the receive operation is complete */
	Reg#(bit) rg_rxne <- mkRegA(1);
	/*doc : reg : Transmit enable bit. This bit will be set when the transmit operation starts and will be reset once the transmit operation is complete */
	Reg#(bit) rg_txe <- mkRegA(0);
	/*doc : reg : SPI Busy bit. This will be set when NCS goes low and will be reset when NCS goes high*/
	Reg#(bit) rg_busy <- mkRegA(0);
	//doc : reg : concatenates all the communication status bits described before for AXI read and write to the memory map register
	Reg#(Bit#(8)) rg_comm_status = concatReg6(rg_over_run,rg_rx_fifo_th,rg_tx_fifo_th,rg_rxne,rg_txe,rg_busy);

	/*doc : reg : RX FIFO full status bit. This bit will be set when RX FIFO is full - has 32 entries */
	Reg#(bit) rg_rx_fifo_full <- mkRegA(0);
	/*doc : reg : RX FIFO half status bit. This bit will be set when RX FIFO has 16 entries */
	Reg#(bit) rg_rx_fifo_half <- mkRegA(0);
	/*doc : reg : RX FIFO quad status bit. This bit will be set when RX FIFO has 8 entries */
	Reg#(bit) rg_rx_fifo_quad <- mkRegA(0);
	/*doc : reg : RX FIFO empty status bit. This bit will be set when RX FIFO is empty */
	Reg#(bit) rg_rx_fifo_empty <- mkRegA(0);
	/*doc : reg : TX FIFO full status bit. This bit will be set when TX FIFO is full - has 32 entries */
	Reg#(bit) rg_tx_fifo_full <- mkRegA(0);
	/*doc : reg : TX FIFO half status bit. This bit will be set when TX FIFO has 16 entries */
	Reg#(bit) rg_tx_fifo_half <- mkRegA(0);
	/*doc : reg : TX FIFO quad status bit. This bit will be set when TX FIFO has 8 entries */
	Reg#(bit) rg_tx_fifo_quad <- mkRegA(0);
	/*doc : reg : TX FIFO empty status bit. This bit will be set when TX FIFO is empty*/
	Reg#(bit) rg_tx_fifo_empty <- mkRegA(0);	
	//doc : reg : concatenates all the FIFO status bits described before for AXI read and write to the memory map register
	Reg#(Bit#(8)) rg_fifo_status = concatReg8(rg_rx_fifo_full,rg_rx_fifo_half,rg_rx_fifo_quad,rg_rx_fifo_empty,
												rg_tx_fifo_full,rg_tx_fifo_half,rg_tx_fifo_quad,rg_tx_fifo_empty);

	/*doc : reg : NCS register. This register will be set by the controller in master mode whereas will be set from ncs io input in slave mode. */
	Reg#(Bit#(1)) rg_ncs <- mkRegA(1);
	/*doc : reg : SCLK register. This register will be set by the controller in master mode whereas will be set from sclk io input in slave mode. */
	Reg#(Bit#(1)) rg_sclk <- mkRegA(0);
	/*doc : reg : Previous SCLK register. This register holds the previous value of rg_sclk to detect the edges in slave mode. */
	Reg#(Bit#(1)) rg_prev_sclk <- mkRegA(0);
	/*doc : reg : This is a clock counter used in master mode to generate SCLK which continuously upcounts till clock prescale value and resets. This counting operation will be active throughout the spi transaction */
	Reg#(Bit#(8)) rg_clk_counter <- mkRegA(0);
	/*doc : wire : This is a write enable wire which will be written at the transmit edge to fire transmit rules. This will be set in master/slave SCLK generation rules */
	Wire#(Bit#(1)) wr_write_en <- mkDWire(0);
	/*doc : wire : This is a read enable wire which will be written at the receive edge to fire receive rules. This will be set in master/slave SCLK generation rules */
	Wire#(Bit#(1)) wr_read_en <- mkDWire(0);
	/*doc : reg : This register is used to enable the transfer of TX data from rg_tx_data register to TX FIFO. This when set, the contents from TX Data is read and equeued to TX FIFO. The arsize/awsize from AXI read and write request is used to decide the enqueue length */
	Reg#(bit) rg_txdata_to_txfifo <- mkRegA(0);
	/*doc : reg : This register is used to enable the transfer of data from RX FIFO to rg_rx_data register. This when set, the contents from RX FIFO is transferred to rg_rx_data register. The arsize/awsize from AXI read and write request is used to decide the dequeue length */
	Reg#(bit) rg_rxfifo_to_rxdata <- mkRegA(0);
	/*doc : reg : This register is used to hold the awsize from rg_tx_data AXI write request. This decides the number of elements that will be enqueued to TX FIFO. */
	Reg#(Bit#(3)) rg_txfifo_enq_size <- mkRegA(0);
	/*doc : reg : This register holds the current TX byte that is being transmitted */
	Reg#(Bit#(8)) rg_curr_tx_byte <- mkRegA(0);
	/*doc : reg : This register holds the current RX byte that is being received */
	Reg#(Bit#(8)) rg_curr_rx_byte <- mkRegA(0);
	/*doc : reg : This register holds the count of number of TX bits transmitted in a SPI transaction */
	Reg#(Bit#(8)) rg_count_tx_data_bits <- mkRegA(0);
	/*doc : reg : This register holds the count of number of RX bits received in a SPI transaction */
	Reg#(Bit#(8)) rg_count_rx_data_bits <- mkRegA(0);
	/*doc : reg : This register holds the count of number of bits transmitted in the current TX byte */
	Reg#(Bit#(3)) rg_count_tx_data <- mkRegA(0);
	/*doc : reg : This register holds the count of number of bits received in the current RX byte */
	Reg#(Bit#(3)) rg_count_rx_data <- mkRegA(0);

	/*doc : reg : This register holds the current bit that is being transmitted */
	Reg#(Bit#(1)) rg_transmit_data <- mkRegA(0);	

	/*doc : reg : This register holds the transmit state of the transmitter */
	Reg#(Transmit_state) rg_transmit_state <- mkRegA(IDLE);
	/*doc : reg : This register holds the receive state of the receiver */
	Reg#(Receive_state) rg_receive_state <- mkRegA(IDLE);
	/*doc : reg : This register holds the SPI state  */
	Reg#(Spi_state) rg_active <- mkRegA(IDLE);
	/*doc : reg : This register is used to detect the write_en edge in slave sclk mode and with clock phase as 0. This is used explicitly as there won't be any change in sclk value at the first write edge. */
	Reg#(Bool) rg_slv_wr_en <- mkRegA(False); // To provide write enable in slave clock mode and clock phase 0 (temp fix as we won't be able to detect the wr_en edge with clk_phase 0)

	MIMOConfiguration cfg = defaultValue;
	cfg.unguarded=True;
	/*doc : FIFO : This is TX MIMO which holds the data to be transmitted */
	MIMO#(4,4,32,Bit#(8)) tx_fifo <- mkMIMO(cfg);
	/*doc : FIFO : This is RX MIMO which holds the received data */
	MIMO#(4,4,32,Bit#(8)) rx_fifo <- mkMIMO(cfg);

	/*doc : Wire : Wire which holds the input from MISO IO pin */
	Wire#(bit) wr_spi_master_in <- mkWire();
	/*doc : Wire : Wire which holds the input from MOSI IO pin */
	Wire#(bit) wr_spi_slave_in <- mkWire();
	/*doc : Wire : Wire which holds the input from SCLK IO pin */
	Wire#(bit) wr_sclk_slave_in <- mkWire();
	/*doc : Wire : Wire which holds the input from NCS IO pin */
	Wire#(bit) wr_ncs_slave_in  <- mkWire();

	/* doc : Wire : Sends the overrun interrupt to PLIC */
	Wire#(bit) wr_rx_over_run_intr <- mkDWire(0);
	/* doc : Wire : Sends the RX FIFO full interrupt to PLIC */
	Wire#(bit) wr_rx_fifo_full_intr <- mkDWire(0);
	/* doc : Wire : sends the RX FIFO half interrupt to PLIC */
	Wire#(bit) wr_rx_fifo_half_intr <- mkDWire(0);
	/* doc : Wire : sends the RX FIFO quad interrupt to PLIC */
	Wire#(bit) wr_rx_fifo_quad_intr <- mkDWire(0);
	/* doc : Wire : sends the RX FIFO empty interrupt to PLIC */
	Wire#(bit) wr_rx_fifo_empty_intr <- mkDWire(0);
	/* doc : Wire : sends the TX FIFO full interrupt to PLIC */
	Wire#(bit) wr_tx_fifo_full_intr <- mkDWire(0);
	/* doc : Wire : sends the TX FIFO half interrupt to PLIC */
	Wire#(bit) wr_tx_fifo_half_intr <- mkDWire(0);
	/* doc : Wire : sends the TX FIFO quad interrupt to PLIC */
	Wire#(bit) wr_tx_fifo_quad_intr <- mkDWire(0);
	/* doc : Wire : sends the TX FIFO empty interrupt to PLIC*/
	Wire#(bit) wr_tx_fifo_empty_intr <- mkDWire(0);

	/* doc : Wire : holds the input qualified (output from IQC module) sclk value in slave mode */
	Wire#(bit) wr_sclk_qual <- mkWire();
	/* doc : Wire : holds the input qualified (output from IQC module) ncs value in slave mode */
	Wire#(bit) wr_ncs_qual0  <- mkWire();
	Wire#(bit) wr_ncs_qual1  <- mkWire();
	Wire#(bit) wr_ncs_qual2  <- mkWire();
	Wire#(bit) wr_ncs_qual3  <- mkWire();
	/* doc : Wire : holds the input qualified (output from IQC module) spi input value in slave mode */
	Wire#(bit) wr_spi_in_qual <- mkWire();

	/*doc : Reg : This register is used to count the setup delay*/
	Reg#(Bit#(8)) rg_set_up_count <- mkRegA(0);
	/*doc : Reg : This register is used to count the hold delay*/
	Reg#(Bit#(8)) rg_hold_count <- mkRegA(0);

`ifdef IQC	
	/*doc : Reg : This register holds the IQC qual cycles which will be followed in all the module inputs */
	Reg#(Bit#(4)) rg_qual_cycles	<- mkRegA(0);
	Ifc_iqc#(1) sspi_mi_qual <- mkiqc(rg_qual_cycles);
	Ifc_iqc#(1) sspi_si_qual <- mkiqc(rg_qual_cycles);
	Ifc_iqc#(1) sspi_ncs_qual <- mkiqc(rg_qual_cycles);
	Ifc_iqc#(1) sspi_sclk_qual <- mkiqc(rg_qual_cycles);
`endif

	(*conflict_free = "rl_transfer_data_from_txreg_to_txfifo,rl_abort_condition"*)
	(*conflict_free = "rl_transmit_idle_to_data_transfer,rl_chip_select_control_master_mode"*)
	(*conflict_free = "rl_transmit_idle_to_data_transfer,rl_chip_select_control_slave_mode"*)
	(*conflict_free = "rl_receive_idle_to_data_receive,rl_chip_select_control_master_mode"*)
	(*conflict_free = "rl_receive_idle_to_data_receive,rl_chip_select_control_slave_mode"*)
	(*conflict_free = "rl_transmit_state,rl_chip_select_control_master_mode"*)
	(*conflict_free = "rl_transmit_state,rl_chip_select_control_slave_mode"*)
	(*conflict_free = "rl_receive_state,rl_chip_select_control_master_mode"*)
	(*conflict_free = "rl_receive_state,rl_chip_select_control_slave_mode"*)
	(*conflict_free = "rl_abort_condition,rl_chip_select_control_master_mode"*)
	(*conflict_free = "rl_abort_condition,rl_chip_select_control_slave_mode"*)
	(*conflict_free = "rl_transmit_idle_to_data_transfer,rl_receive_idle_to_data_receive"*)
	(*conflict_free = "rl_transmit_idle_to_data_transfer,rl_abort_condition"*)	
	(*conflict_free = "rl_transmit_state,rl_receive_idle_to_data_receive"*)
	(*conflict_free = "rl_receive_state,rl_transmit_idle_to_data_transfer"*)
	(*conflict_free = "rl_transmit_state,rl_receive_state"*)
	(*conflict_free = "rl_receive_idle_to_data_receive,rl_abort_condition"*)
	(*conflict_free = "rl_receive_state,rl_abort_condition"*)
	(*conflict_free = "rl_transmit_state,rl_abort_condition"*)
	(*conflict_free = "rl_transfer_data_from_rxfifo_to_rxreg,rl_chip_select_control_master_mode"*)
	(*conflict_free = "rl_transfer_data_from_rxfifo_to_rxreg,rl_chip_select_control_slave_mode"*)
	(*conflict_free = "rl_transfer_data_from_rxfifo_to_rxreg,rl_abort_condition"*)
	(*conflict_free = "rl_transfer_data_from_rxfifo_to_rxreg,rl_receive_state"*)
	(*conflict_free = "rl_transfer_data_from_rxfifo_to_rxreg,rl_rx_fifo_threshold_updates"*)
	(*conflict_free = "rl_chip_select_control_master_mode,rl_rx_fifo_threshold_updates"*)
	(*conflict_free = "rl_chip_select_control_slave_mode,rl_rx_fifo_threshold_updates"*)
	(*conflict_free = "rl_chip_select_control_master_mode,rl_tx_fifo_threshold_updates"*)
	(*conflict_free = "rl_chip_select_control_slave_mode,rl_tx_fifo_threshold_updates"*)
	(*conflict_free = "rl_chip_select_control_master_mode,rl_spi_clock_generator_master_mode"*)
	(*conflict_free = "rl_chip_select_control_master_mode,rl_spi_clock_generator_slave_mode"*)
	(*conflict_free = "rl_chip_select_control_slave_mode,rl_spi_clock_generator_master_mode"*)
	(*conflict_free = "rl_chip_select_control_slave_mode,rl_spi_clock_generator_slave_mode"*)
	(*conflict_free = "rl_mi_qualification,rl_receive_state"*)
	(*conflict_free = "rl_si_qualification,rl_receive_state"*)
	(*conflict_free = "rl_si_qualification,rl_mi_qualification"*)
	rule rl_delay_sclk;
        for (Integer i = 1; i<`sclk_delay; i = i + 1) begin
          val_sclk_delay[i] <= val_sclk_delay[i-1];
          sclkEn_delay[i] <= sclkEn_delay[i-1];
        end
        val_sclk_delay[0] <= rg_sclk;
        sclkEn_delay[0] <= rg_sclk_output_enable;
    endrule

	rule rl_delay_mosi;
        for (Integer i = 1; i<`mosi_delay; i = i + 1) begin
          val_mosi_delay[i] <= val_mosi_delay[i-1];
          mosiEn_delay[i] <= mosiEn_delay[i-1];
        end
        val_mosi_delay[0] <= rg_transmit_data;
        mosiEn_delay[0] <= rg_mosi_output_enable;
    endrule

	/*doc:rule: This rule fires during the recieve state and when miso is configure as input. wr_spi_master_in value is read and sent to input qualification control module, if IQC is enabled else wr_spi_master_in value is directly assigned to wr_spi_in_qual  */
	rule rl_mi_qualification(rg_receive_state == DATA_RECEIVE && rg_miso_output_enable == 0);
	`ifdef IQC
		let temp <- sspi_mi_qual.qualify(wr_spi_master_in);
		wr_spi_in_qual <= temp;
	`else
		wr_spi_in_qual <= wr_spi_master_in;
	`endif
	endrule

	/*doc:rule: This rule fires during the recieve state and when mosi is configure as input. wr_spi_slave_in value is read and sent to input qualification control module, if IQC is enabled else wr_spi_slave_in value is directly assigned to wr_spi_in_qual  */
	rule rl_si_qualification(rg_receive_state == DATA_RECEIVE && rg_mosi_output_enable == 0);
	`ifdef IQC
		let temp <- sspi_si_qual.qualify(wr_spi_slave_in);	
		wr_spi_in_qual <= temp;
	`else
		wr_spi_in_qual <= wr_spi_slave_in;
	`endif
	endrule

	/*doc:rule: This rule fires when NCS is output. This rule does the ncs output generation. When rg_spi_en is set, rg_ncs is reset, rg_busy is set and assigns the rg_counter to prescale - 1 to start the rg_counter from zero during the sclk generation. When rg_spi_en is zero and if the rg_counter is prescale - 1, it sets the rg_ncs register and resets the rg_busy register. This is wait for the last sclk to complete and reset the parameters for next SPI transaction. */
	rule rl_chip_select_control_master_mode(rg_ncs_output_enable == 1);
		if(rg_spi_en == 1)
		begin
			rg_ncs <= 0;
			if(rg_ncs != 0) begin
				rg_clk_counter <= rg_prescaller-1;
				rg_busy <= 1;
		   end
		end
		else begin
			if(rg_clk_counter == rg_prescaller) begin
				rg_ncs <= 1;
				rg_busy <= 0;
			end
		end
	endrule
	
	/*doc:rule: This rule fires when SCLK is output. This rule does the sclk output generation. when rg_ncs is set, rg_sclk is held with clk_polarity value. when rg_ncs is reset, rg_counter continuosly counts from 0 to prescale - 1 and generates the transmit (write edge) and receive (read edge) edges at zero and half prescale values. During the setup and hold phase, sclk value is equal to clock polarity  */
	rule rl_spi_clock_generator_master_mode(rg_sclk_output_enable == 1);
		Bit#(1) temp_clk_pol = rg_clk_polarity;
		Bit#(1) temp_clk_phase = rg_clk_phase;
		Bit#(8) temp_prescaller = rg_prescaller;
		if(rg_ncs == 1)
			rg_sclk <= temp_clk_pol;
		else begin
			Bit#(8) temp_half_count = zeroExtend(temp_prescaller[7:1]);
			Bit#(1) lv_sclk_val = rg_sclk;
			if(rg_clk_counter == temp_prescaller) begin
				if(rg_active == HOLD_PHASE) begin //Last SCLK to be sent, after this rg_sclk will have clk_polarity value
					rg_active <= IDLE;
					lv_sclk_val = rg_clk_polarity;
				end
				else
					lv_sclk_val = temp_clk_phase == 0 ? temp_clk_pol : ~temp_clk_pol;
				if(rg_spi_en == 1)
					wr_write_en <= 1;
			end
			else if(rg_clk_counter == temp_half_count) begin
				lv_sclk_val = ~rg_sclk;
				if(rg_spi_en == 1)
					wr_read_en <= 1;
				if(rg_active == WAIT) //setup delay is done. until now rg_sclk will have have clk_polarity value.
					rg_active <= ACTIVE;
			end
			if(rg_active == ACTIVE || rg_active == HOLD_PHASE) //Active SPI transaction (no setup or hold phase)
				rg_sclk <= lv_sclk_val;
			else // setup or hold phase
				rg_sclk <= rg_clk_polarity;
			if(rg_clk_counter == temp_prescaller)
				rg_clk_counter <= 0;
			else
				rg_clk_counter <= rg_clk_counter + 1;
		end
	endrule

	/*doc:rule : This rule fires when ncs is input. When rg_spi_en is set, wr_ncs_qual value is assigned to rg_ncs register */
	rule rl_chip_select_control_slave_mode(rg_ncs_output_enable == 0);
		if(rg_spi_en == 1) begin
		       
	     Bit#(1)  lv_ncs_qual=case (rg_slave_select)
              0 : wr_ncs_qual0;
              1 : wr_ncs_qual1;
              2 : wr_ncs_qual2;
	      3 : wr_ncs_qual3;
                default: wr_ncs_qual0; 
		endcase; 
  
			rg_ncs <= lv_ncs_qual;
			if(rg_ncs == 1) begin
			  rg_busy <= 1;
			  //if(rg_clk_phase == 0)
				//  wr_write_en <= 1;
			end
		end
		else begin
			rg_ncs <= 1;
			rg_busy <= 0;
			rg_slv_wr_en <= False;
		end
	endrule

	/*doc:rule : This rule fires when sclk is input. When rg_spi_en is set, wr_sclk_qual value is assigned to rg_sclk and rg_prev_sclk is also updated. wr_write_en and wr_read_en are updated based on the rising or falling edge of SCLK input */
	rule rl_spi_clock_generator_slave_mode(rg_sclk_output_enable == 0 && rg_spi_en == 1);
		let temp = wr_sclk_qual;
		rg_sclk <= temp;
		rg_prev_sclk <= rg_sclk;
		if((temp ^ rg_sclk) == 1) begin
			if((rg_clk_polarity ^ rg_clk_phase) == 1) begin
				if(rg_prev_sclk == 0) 	//Rising edge
					wr_write_en <= 1;
				else					//Falling edge
					wr_read_en <= 1;
			end
			else begin
				if(rg_prev_sclk == 1)	//Falling edge
					wr_write_en <= 1;
				else					//Rising edge
					wr_read_en <= 1;
			end
		end
		else if(rg_ncs == 0 && rg_clk_phase == 0 && rg_slv_wr_en == False && (rg_transmit_state == DATA_TRANSMIT && rg_comm_mode != 1)) begin //to detect the very first write enable when clk_phase is zero as there won't be any toggle.
			wr_write_en <= 1;
			rg_slv_wr_en <= True;
		end
	endrule

	/*doc:rule : This rule updates the TX FIFO status, interrupt and FIFO threshold wires and registers */
	rule rl_tx_fifo_threshold_updates;
		let temp_fifo_count = tx_fifo.count;
		if(temp_fifo_count == 32) begin
			rg_tx_fifo_full <= 1;
			wr_tx_fifo_full_intr <= 1;
		end
		else if(temp_fifo_count == 16) begin
			rg_tx_fifo_half <= 1;
			wr_tx_fifo_half_intr <= 1;
		end
		else if(temp_fifo_count == 8) begin
			rg_tx_fifo_quad <= 1;
			wr_tx_fifo_quad_intr <= 1;
		end
		else if(temp_fifo_count == 0) begin
			rg_tx_fifo_empty <= 1;
			wr_tx_fifo_empty_intr <= 1;
		end
		else begin
			rg_tx_fifo_empty <= 0;
			rg_tx_fifo_quad <= 0;
			rg_tx_fifo_half <= 0;
			rg_tx_fifo_full <= 0;
		end
		if(temp_fifo_count >= 24)
				rg_tx_fifo_th <= 3;
		else if(temp_fifo_count >= 16)
				rg_tx_fifo_th <= 2;
		else if(temp_fifo_count >= 8)
				rg_tx_fifo_th <= 1;
		else
				rg_tx_fifo_th <= 0;
	endrule

	/*doc:rule : This rule updates the RX FIFO status, interrupt and FIFO threshold wires and registers */
	rule rl_rx_fifo_threshold_updates;
		let temp_fifo_count = rx_fifo.count;
		if(temp_fifo_count == 32) begin
			rg_rx_fifo_full <= 1;
			wr_rx_fifo_full_intr <= 1;
		end
		else if(temp_fifo_count == 16) begin
			rg_rx_fifo_half <= 1;
			wr_rx_fifo_half_intr <= 1;
		end
		else if(temp_fifo_count == 8) begin
			rg_rx_fifo_quad <= 1;
			wr_rx_fifo_quad_intr <= 1;
		end
		else if(temp_fifo_count == 0) begin
			rg_rx_fifo_empty <= 1;
			wr_rx_fifo_empty_intr <= 1;
		end
		else begin
			rg_rx_fifo_empty <= 0;
			rg_rx_fifo_quad <= 0;
			rg_rx_fifo_half <= 0;
			rg_rx_fifo_full <= 0;
		end
		if(temp_fifo_count >= 24)
				rg_rx_fifo_th <= 3;
		else if(temp_fifo_count >= 16)
				rg_rx_fifo_th <= 2;
		else if(temp_fifo_count >= 8)
				rg_rx_fifo_th <= 1;
		else
				rg_rx_fifo_th <= 0;
	endrule	

	/*doc:rule : This rule fires when rg_txdata_to_txfifo register is set and transfers the data from rg_tx_data to TX FIFO. The enqueue size is read from rg_txfifo_enq_size */
	rule rl_transfer_data_from_txreg_to_txfifo(rg_txdata_to_txfifo == 1);
		Bit#(32) temp_tx = rg_tx_data;
		Vector#(4,Bit#(8)) temp = newVector();
		if(rg_txfifo_enq_size == 4) begin
			if(rg_lsbfirst == 1) begin
				temp[0] = temp_tx[7:0];
				temp[1] = temp_tx[15:8];
				temp[2] = temp_tx[23:16];
				temp[3] = temp_tx[31:24];
			end
			else begin
				temp[0] = temp_tx[31:24];
				temp[1] = temp_tx[23:16];
				temp[2] = temp_tx[15:8];
				temp[3] = temp_tx[7:0];
			end
			tx_fifo.enq(4,temp);
		end
		else if(rg_txfifo_enq_size == 2) begin
			if(rg_lsbfirst == 1) begin
				temp[0] = temp_tx[7:0];
				temp[1] = temp_tx[15:8];
			end
			else begin
				temp[0] = temp_tx[15:8];
				temp[1] = temp_tx[7:0];
			end
			tx_fifo.enq(2,temp);
		end
		else begin
			temp[0] = temp_tx[7:0];
			tx_fifo.enq(1,temp);
		end
		`logLevel(sspi, 0, $format("SSPI : Transfer data from tx reg to tx fifo : ready = %b and data = %x : FIFO count : %d \n",tx_fifo.enqReady,temp,tx_fifo.enqReadyN(4)))	
		rg_txdata_to_txfifo <= 0; 
	endrule

	/*doc:rule: This rule fires when rg_rxfifo_to_rxdata is set and transfers 32-bit data (four entries) from RX FIFO to rg_rx_data. The value is just read and not dequeued. */
	rule rl_transfer_data_from_rxfifo_to_rxreg(rg_rxfifo_to_rxdata == 1);
		if(rx_fifo.deqReadyN(1)) begin
			Bit#(32) temp;
			if(rg_lsbfirst == 1)
				temp = {rx_fifo.first[3],rx_fifo.first[2],rx_fifo.first[1],rx_fifo.first[0]};
			else
				temp = {rx_fifo.first[0],rx_fifo.first[1],rx_fifo.first[2],rx_fifo.first[3]};
			rg_rx_data <= temp;
		end
		rg_over_run <= 0;
		rg_rxfifo_to_rxdata <= 0;
	endrule

	//rule rl_dump_required_values;
	//	`logLevel(sspi, 0, $format("SSPI : sclk = %b; clk_count = %d; tx_fifo_deq = %b; tx_state = %b; tx_bits = %d; rx_fifo_count : %d; spi_en = %b; ncs = %b tx_data_reg = %x rx_data_reg = %x \n",rg_sclk,rg_clk_counter,tx_fifo.deqReadyN(4),rg_transmit_state,rg_total_bit_tx,rx_fifo.count,rg_spi_en,rg_ncs,rg_tx_data,rg_rx_data)) 
	//endrule

	/*doc:rule: This rule fires when setup delay set in clock register is not zero and also till rg_set_up_count is rg_cs_t_delay -1. This rule fires only during the write edges (wr_write_en == 1) set in sclk generation rule */
	rule rl_set_up_time(((rg_transmit_state == IDLE && rg_total_bit_tx != 0 && rg_comm_mode != 2 ) || (rg_receive_state == IDLE && rg_total_bit_rx != 0 && rg_comm_mode == 2)) && rg_ncs == 0 && rg_spi_en == 1 && wr_write_en == 1 && rg_set_up_count < rg_cs_t_delay);
		rg_set_up_count <= rg_set_up_count + 1;
		rg_active <= SETUP_PHASE;
	endrule

	/*doc:rule: This rule fires when setup delay is met, transmit state is IDLE, TX FIFO has atleast one entry and total bits to be transmitted is not zero. This rule changes the transmit state from IDLE to DATA TRANSMIT, dequeues the first byte from TX FIFO, sets rg_txe register and resets the bit counters used in transmit rule. */
	rule rl_transmit_idle_to_data_transfer(tx_fifo.deqReadyN(1) && rg_transmit_state == IDLE && rg_total_bit_tx != 0 && rg_ncs == 0 && rg_spi_en == 1 && rg_set_up_count == rg_cs_t_delay);
		rg_transmit_state <= DATA_TRANSMIT;
		rg_curr_tx_byte <= tx_fifo.first[0];
		tx_fifo.deq(1);
		rg_count_tx_data_bits <= 0;
		rg_count_tx_data <= 0;
		rg_txe <= 1;
		//rg_set_up_count <= 0;
		if(rg_cs_t_delay == 0)
			rg_active <= ACTIVE;
		else
			rg_active <= WAIT;
		`logLevel(sspi, 0, $format("SSPI : tx_idle to transmit : %b tx bits : %d \n",tx_fifo.deqReadyN(4),rg_total_bit_tx)) 
	endrule
	
	//===================Transmit state==================//
	/*doc:rule: This rule fires when rg_transmit_state is DATA TRANSMIT and wr_write_en is set. Data is read by byte from TX FIFO and left or right shifted based on LSB/MSB first configuration. When the bit count reaches total bits to be transmitted, transmit state is changed to DONE, rg_txe is reset and if it is only transmit (communication mode is zero), rg_active is also changed from ACTIVE to HOLD PHASE.*/
	rule rl_transmit_state(rg_transmit_state == DATA_TRANSMIT && rg_ncs == 0 && rg_spi_en == 1 && wr_write_en == 1);
		if(rg_lsbfirst == 1)
			rg_transmit_data <= rg_curr_tx_byte[0];
		else
			rg_transmit_data <= rg_curr_tx_byte[7];
		if(rg_count_tx_data_bits == rg_total_bit_tx - 1) begin
			rg_transmit_state <= TRANSMIT_DONE;
			rg_txe <= 0;
			if(rg_comm_mode == 0)
				rg_active <= HOLD_PHASE;
		end
		else begin
			if(rg_count_tx_data == 7) begin
				if(tx_fifo.deqReadyN(1)) begin
					rg_curr_tx_byte <= tx_fifo.first[0];
					tx_fifo.deq(1);
			//		rg_count_tx_data <= 0;
				end
				else begin
					rg_transmit_state <= TRANSMIT_DONE;
					rg_txe <= 0;
					if(rg_comm_mode == 0)
						rg_active <= HOLD_PHASE;
				end
			end
			else begin
				if(rg_lsbfirst == 1)
					rg_curr_tx_byte <= rg_curr_tx_byte >> 1;
				else
					rg_curr_tx_byte <= rg_curr_tx_byte << 1;
			end
			rg_count_tx_data <= rg_count_tx_data + 1;
			rg_count_tx_data_bits <= rg_count_tx_data_bits + 1;
		end
		`logLevel(sspi, 0, $format("SSPI : transmit state : %b bit count %d and data count %d and data transmitted %d \n",rg_transmit_state,rg_count_tx_data_bits,rg_count_tx_data,rg_transmit_data)) 
	endrule

	/*doc:rule: This rule fires when receive state is IDLE, RX FIFO can enqueue atleast one byte, wr_write_en is set. If communication mode is not only receive, transmit state should be TRANSMIT DONE. If the communication mode is only receive, then setup delay should be met. This rule changes the receive state to DATA RECEIVE, rg_rxne is reset and resets the bit counters used in receive rule.*/
	rule rl_receive_idle_to_data_receive(wr_write_en == 1 && rx_fifo.enqReadyN(1) && rg_receive_state == IDLE && rg_total_bit_rx != 0 && (rg_comm_mode != 2'b10 || rg_transmit_state == TRANSMIT_DONE) && rg_ncs == 0 && rg_spi_en == 1 && (rg_comm_mode != 2'b01 || rg_set_up_count == rg_cs_t_delay)) ;
		rg_receive_state <= DATA_RECEIVE;
		rg_count_rx_data_bits <= 0;
		rg_count_rx_data <= 0;
		rg_rxne <= 0;
		//rg_set_up_count  <= 0;
		rg_active <= ACTIVE;
		`logLevel(sspi, 0, $format("SSPI : rx_idle to receive : %b rx bits : %d \n",tx_fifo.enqReadyN(4),rg_total_bit_rx)) 
	endrule	

	//===================Receive state==================//
	/*doc:rule: This rule fires when receive state is DATA RECEIVE and it is read edge (wr_read_en is set). The input bit is appended to rg_curr_rx_byte and shifted left or right based on LSB/MSB byte. The received data is enqueued by byte to RX FIFO and overrun is set when a byte couldn't be enqueued into the RX FIFO. When all the required bits are received, the receive state is changed to RECEIVE DONE, rg_curr_rx_byte is enqueued to RX FIFO, rg_rxne is set, rg_active is changed to HOLD PHASE and rg_rxfifo_to_rxdata is set. */
	rule rl_receive_state(rg_receive_state == DATA_RECEIVE && wr_read_en == 1 && rg_ncs == 0 && rg_spi_en == 1);
		Bit#(8) temp_rx_data = 0;
		if(rg_lsbfirst == 1)
			temp_rx_data = {wr_spi_in_qual, rg_curr_rx_byte[6:0]};
		else
			temp_rx_data = {rg_curr_rx_byte[7:1],wr_spi_in_qual};
		rg_count_rx_data_bits <= rg_count_rx_data_bits + 1;
		if(rg_count_rx_data_bits == rg_total_bit_rx - 1) begin
				if(rx_fifo.enqReadyN(1)) begin
					Vector#(4,Bit#(8)) temp = newVector();
					temp[0] = temp_rx_data[7:0];
					temp[1] = 0;
					temp[2] = 0;
					temp[3] = 0;
					rx_fifo.enq(1,temp);	
					rg_over_run <= 0;
				end
				else begin
					rg_over_run <= 1;
					wr_rx_over_run_intr <= 1;
				end
				rg_receive_state <= RECEIVE_DONE;
				rg_active <= HOLD_PHASE;
				rg_rxne <= 1;
				rg_rxfifo_to_rxdata <= 1;
		end
		else begin
			if(rg_count_rx_data == 7) begin
				if(rx_fifo.enqReadyN(1)) begin
					Vector#(4,Bit#(8)) temp = newVector();
					temp[0] = temp_rx_data[7:0];
					temp[1] = 0;
					temp[2] = 0;
					temp[3] = 0;
					rx_fifo.enq(1,temp);
					rg_count_rx_data <= 0;
					rg_over_run <= 0;
				end
				else begin
					rg_receive_state <= RECEIVE_DONE;
					rg_active <= HOLD_PHASE;
					rg_rxne <= 1;
					rg_over_run <= 1;
					wr_rx_over_run_intr <= 1;
				end
			end
			else begin
				rg_count_rx_data <= rg_count_rx_data + 1;
				if(rg_lsbfirst == 1)
					rg_curr_rx_byte <= temp_rx_data >> 1;
				else
					rg_curr_rx_byte <= temp_rx_data << 1;	
				rg_over_run <= 0;
			end
		end
		`logLevel(sspi, 0, $format("SSPI : receive state : %b rx bits : %d  rx data : %d total_rx_data %d current data %b \n",rg_receive_state,rg_count_rx_data_bits,rg_count_rx_data,rg_total_bit_rx,temp_rx_data)) 
	endrule	

	/*doc:rule : This rule fires when Transmit and recive states are done based on the communication modes. This rule also does the hold delay count at write edges and once the hold delay is met, resets rg_spi_en, resets rg_hold_count and changes transmit and receive states to IDLE */
	rule rl_abort_condition(rg_spi_en == 1 && (((rg_comm_mode == 2'b10 || rg_comm_mode == 2'b11) && rg_transmit_state == TRANSMIT_DONE && rg_receive_state == RECEIVE_DONE) || (rg_comm_mode == 2'b00 && rg_transmit_state == TRANSMIT_DONE) || (rg_comm_mode == 2'b01 && rg_receive_state == RECEIVE_DONE)));
		if(rg_hold_count == rg_t_cs_delay) begin
			rg_transmit_state <= IDLE;
			rg_receive_state <= IDLE;
			rg_spi_en <= 0;
			rg_hold_count <= 0;
         rg_set_up_count <= 0;  
		end
		else if(wr_write_en == 1)
			rg_hold_count <= rg_hold_count + 1;
	endrule

	method ActionValue#(Bool) mav_write_req(Bit#(addr_width) addr, Bit#(data_width) data, Bit#(2) size);
		Bool succ = True;
		if(addr[7:0] == `Communication_control && size == 2)
			rg_comm_ctrl <= truncate(data);
		else if(addr[7:0] == `Clock_control && size == 2)
			rg_clk_ctrl <= truncate(data);
		else if(addr[7:0] == `TX_data_rg) begin
			rg_tx_data <= truncate(data);
			Bit#(3) temp_size = size == 2 ? 4 : zeroExtend(size + 1);
			rg_txfifo_enq_size <= temp_size;
			if(tx_fifo.enqReadyN(unpack(temp_size)))
				rg_txdata_to_txfifo <= 1;
			else
				succ = False;
		end
		else if(addr[7:0] == `Interrupt_enable && size == 1)
			rg_intr_en <= truncate(data);
		`ifdef IQC
		else if(addr[7:0] == `Input_qualification && size == 0)
			rg_qual_cycles <= truncate(data);
		`endif
		else
			succ = False;
		`logLevel( sspi, 0, $format("SSPI : write req : addr = %h, data = %h, succ = %h \n",addr,data,succ))   
		return succ;		
	endmethod

	method ActionValue#(Tuple2#(Bool,Bit#(data_width))) mav_read_req(Bit#(addr_width) addr, Bit#(2) size);
		Bool succ = True;
		Bit#(data_width) data = 0;
		if(addr[7:0] == `Communication_control && size == 2)
			data = duplicate(rg_comm_ctrl);
		else if(addr[7:0] == `Clock_control && size == 2)
			data = duplicate(rg_clk_ctrl);
		else if(addr[7:0] == `RX_data_rg) begin
			Bit#(3) temp_size = size == 2 ? 4 : zeroExtend(size + 1);
			`logLevel( sspi, 0, $format(" Read req RX temp_size = %d ; rx_fifo count = %d; data = %x;\n",temp_size,rx_fifo.count,data))
			if(rx_fifo.count >= unpack(zeroExtend(temp_size))) begin
				rx_fifo.deq(unpack(temp_size));
				if(rg_lsbfirst == 0) begin
					if(size == 0)
						data = duplicate(rg_rx_data[31:24]);
					else if(size == 1)
						data = duplicate(rg_rx_data[31:16]);
					else
						data = duplicate(rg_rx_data);
				end
				else
					data = duplicate(rg_rx_data);
				rg_rxfifo_to_rxdata <= 1;
			end
			else
				succ = False;
			$display($time," Read req RX temp_size = %d ; rx_fifo count = %d; data = %x;\n",temp_size,rx_fifo.count,data);
		end
		else if(addr[7:0] == `FIFO_status && size == 0)
			data = duplicate(rg_fifo_status);
		else if(addr[7:0] == `Communication_status && size == 0)
			data = duplicate(rg_comm_status);
		else if(addr[7:0] == `Interrupt_enable && size == 1)
			data = duplicate(rg_intr_en);
		`ifdef IQC
		else if(addr[7:0] == `Input_qualification && size == 0)
			data = zeroExtend(rg_qual_cycles);
		`endif
		else
			succ = False;
		`logLevel( sspi, 0, $format("Sspi : read req : addr = %h, data = %h, succ = %h \n",addr,data,succ))   
		return tuple2(succ,data);		
	endmethod
    
 	interface subifc_io = interface Ifc_sspi_io;
		//mosi input output
		method bit mosi_outen;
			return mosiEn_delay[`mosi_delay-1];
		endmethod
 		method bit mosi_out;
 			return val_mosi_delay[`mosi_delay-1];
 		endmethod
		method Action mosi_in(bit val);
			wr_spi_slave_in <= val;
		endmethod
		//sclk input output
		method bit sclk_outen;
			return sclkEn_delay[`sclk_delay-1];
		endmethod
 		method bit sclk_out;
 			return val_sclk_delay[`sclk_delay-1];
 		endmethod
		method Action sclk_in(bit val);
		`ifdef IQC
			let temp <- sspi_sclk_qual.qualify(val);
			wr_sclk_qual <= temp;
		`else
			wr_sclk_qual <= val;
		`endif
		endmethod
		//miso input output
		method bit miso_outen;
			return rg_miso_output_enable;
		endmethod
 		method Action miso_in(bit val);
 			wr_spi_master_in <= val;
 		endmethod
		method bit miso_out;
			return rg_transmit_data;
		endmethod
		//ncs input output
		//Multiple slaves of SPI (4)
		
		method bit ncs_outen0;
		if(rg_slave_select == 0)  
			return rg_ncs_output_enable;
		else
		        return 0;   
		endmethod
		
		method bit ncs_out0;
		if(rg_slave_select == 0)
 			return rg_ncs;
 		else
		        return 1;
 		endmethod
 		
 		method Action ncs_in0(bit val);
 		//if((rg_slave_select == 0)) begin
		if(rg_ncs_output_enable == 0) begin
		`ifdef IQC
			let temp <- sspi_ncs_qual.qualify(val);
			wr_ncs_qual0 <= temp;
		`else
			wr_ncs_qual0 <= val;
		`endif
		end
		//end
		endmethod
 		
		method bit ncs_outen1;
		if(rg_slave_select == 1)
			return rg_ncs_output_enable;
		else
		        return 0;
		endmethod
		
		method bit ncs_out1;
		if(rg_slave_select == 1)
 			return rg_ncs;
 		else
		        return 1;
 		endmethod
		
		method Action ncs_in1(bit val);
		//if(rg_slave_select == 1) begin
		if(rg_ncs_output_enable == 0) begin
		`ifdef IQC
			let temp <- sspi_ncs_qual.qualify(val);
			wr_ncs_qual1 <= temp;
		`else
			wr_ncs_qual1 <= val;
		`endif
		end
		//end
		endmethod
		
		method bit ncs_outen2;
		if(rg_slave_select == 2)
			return rg_ncs_output_enable;
		else
		        return 0;
		endmethod
		
		method bit ncs_out2;
		if(rg_slave_select == 2)
 			return rg_ncs;
 		else
		        return 1;
 		endmethod
 		
 		method Action ncs_in2(bit val);
 		//if(rg_slave_select == 2) begin
		if(rg_ncs_output_enable == 0) begin
		`ifdef IQC
			let temp <- sspi_ncs_qual.qualify(val);
			wr_ncs_qual2 <= temp;
		`else
			wr_ncs_qual2 <= val;
		`endif
		end
		//end
		endmethod
		
		method bit ncs_outen3;
		if(rg_slave_select == 3)
			return rg_ncs_output_enable;
		else
		        return 0;
		endmethod
		
		method bit ncs_out3;
		if(rg_slave_select == 3)
 			return rg_ncs;
 		else
		        return 1;
 		endmethod
 		
 		method Action ncs_in3(bit val);
 		//if(rg_slave_select == 3) begin
		if(rg_ncs_output_enable == 0) begin
		`ifdef IQC
			let temp <- sspi_ncs_qual.qualify(val);
			wr_ncs_qual3 <= temp;
		`else
			wr_ncs_qual3 <= val;
		`endif
		end
		//end
		endmethod
	endinterface;
	method mv_sb_sspi_interrupt = ((wr_rx_over_run_intr & rg_rx_over_run_err_intr_en) | (wr_rx_fifo_full_intr & rg_rx_fifo_full_intr_en) | (wr_rx_fifo_half_intr & rg_rx_fifo_half_intr_en) | (wr_rx_fifo_quad_intr & rg_rx_fifo_quad_intr_en) | 
								(wr_rx_fifo_empty_intr & rg_rx_fifo_empty_intr_en) | (wr_tx_fifo_full_intr & rg_tx_fifo_full_intr_en) | (wr_tx_fifo_half_intr & rg_tx_fifo_half_intr_en) | (wr_tx_fifo_quad_intr & rg_tx_fifo_quad_intr_en) |
								(wr_tx_fifo_empty_intr & rg_tx_fifo_empty_intr_en));
  
endmodule : mk_sspi

	//axi4lite
	interface Ifc_sspi_axi4lite#(numeric type addr_width, numeric type data_width, numeric type user_width);
		interface Ifc_sspi_io io;
		method Bit#(1) sb_sspi_interrupt;
		interface AXI4_Lite_Slave_IFC#(addr_width, data_width, user_width) slave;
	endinterface

	module mksspi_axi4lite `ifdef testmode #(Bool test_mode, Clock test_clk) `endif (Ifc_sspi_axi4lite#(addr_width,data_width,user_width))
			provisos(Add#(a__, 32, data_width),
					 Add#(b__,  4, data_width),
					 Mul#(32, c__, data_width),
					 Mul#( 8, d__, data_width),
					 Mul#(16, e__, data_width),
					 Mul#( 4, f__, data_width),
					 Add#(16, g__, data_width),
					 Add#(h__, 1, data_width)
					);
		GatedClockIfc spi_clk_gated <- mkGatedClockFromCC(False);
		Ifc_sspi#(addr_width,data_width) sspi <- mk_sspi(clocked_by spi_clk_gated.new_clk);
		AXI4_Lite_Slave_Xactor_IFC#(addr_width,data_width,user_width)  s_xactor <- mkAXI4_Lite_Slave_Xactor();
		Reg#(bit) rg_clk_en <- mkRegA(0);
		
		
	    rule clock_en;    
	       spi_clk_gated.setGateCond(unpack(rg_clk_en));	         
	       endrule

		rule read_request;
		        Bool succ = False;
		        Bit#(data_width) data = 0 ; 
	  		let req <- pop_o (s_xactor.o_rd_addr);
	       if (req.araddr[7:0] == `SPI_Clk_En && req.arsize == 0) begin 
		           succ = True; 
		           data = duplicate({7'b0,rg_clk_en});  	         
	         end 
	          else begin  		
      		          {succ,data} <- sspi.mav_read_req(req.araddr,unpack(truncate(req.arsize)));
      		     end 
	  		let resp= AXI4_Lite_Rd_Data {rresp:succ?AXI4_LITE_OKAY:AXI4_LITE_SLVERR, 
                                    rdata:data, ruser: ?};
	  		s_xactor.i_rd_data.enq(resp);
     	endrule

     	rule write_request;
     	        Bool succ = False;
       		let addreq <- pop_o(s_xactor.o_wr_addr);
       		let datareq <- pop_o(s_xactor.o_wr_data);
       		if (addreq.awaddr[7:0] == `SPI_Clk_En && addreq.awsize == 0) begin 
       		    rg_clk_en <= truncate(datareq.wdata); 
       		     succ = True;
       		 end 
       		 else begin 
       		      succ <- sspi.mav_write_req(addreq.awaddr, datareq.wdata,unpack(truncate(addreq.awsize)));
       		     end 
       		let resp = AXI4_Lite_Wr_Resp {bresp: succ?AXI4_LITE_OKAY:AXI4_LITE_SLVERR, buser: ?};
       		s_xactor.i_wr_resp.enq(resp);
     	endrule
		interface io = sspi.subifc_io;
		method sb_sspi_interrupt = sspi.mv_sb_sspi_interrupt;
     	interface slave = s_xactor.axi_side;
	endmodule

	//axi4
	interface Ifc_sspi_axi4#(numeric type addr_width, numeric type data_width, numeric type user_width);
		interface Ifc_sspi_io io;
		method Bit#(1) sb_sspi_interrupt;
		interface AXI4_Slave_IFC#(addr_width,data_width,user_width)	slave;
	endinterface
	module mksspi_axi4(Ifc_sspi_axi4#(addr_width,data_width,user_width))
			provisos(Add#(a__, 32, data_width),
					 Add#(b__,  4, data_width),
					 Mul#(32, c__, data_width),
					 Mul#( 8, d__, data_width),
					 Mul#(16, e__, data_width),
					 Mul#( 4, f__, data_width),
					 Add#(16, g__, data_width)
					);
		Ifc_sspi#(addr_width,data_width) sspi <- mk_sspi;
		AXI4_Slave_Xactor_IFC#(addr_width,data_width,user_width) s_xactor<-mkAXI4_Slave_Xactor();
		Reg#(Bit#(8)) rg_rdburst_count <- mkRegA(0);
		Reg#(Bit#(8)) rg_wrburst_count <- mkRegA(0);

		Reg#(AXI4_Rd_Addr#(addr_width,user_width)) rg_rdpacket <- mkRegA(?);
 		Reg#(AXI4_Wr_Addr#(addr_width,user_width)) rg_wrpacket <- mkRegA(?);


		rule read_request(rg_rdburst_count==0);
			let req<-pop_o(s_xactor.o_rd_addr);
			let {succ,data}<-sspi.mav_read_req(req.araddr,unpack(truncate(req.arsize)));
			rg_rdpacket<=req;	

			if(req.arlen!=0)
				rg_rdburst_count<=1;
			let resp= AXI4_Rd_Data{rresp:succ?AXI4_OKAY:AXI4_SLVERR, rid:req.arid,rlast:(req.arlen==0),rdata:data, ruser: ?};
			s_xactor.i_rd_data.enq(resp);
		endrule
		
		rule read_burst(rg_rdburst_count!=0);
			let rd_req=rg_rdpacket;
			let {succ,data}<-sspi.mav_read_req(rd_req.araddr,unpack(truncate(rd_req.arsize)));
			succ=False;
			if(rg_rdburst_count==rd_req.arlen)
				rg_rdburst_count<=0;
			else
				rg_rdburst_count<=rg_rdburst_count+1;
			let resp= AXI4_Rd_Data{rresp:succ?AXI4_OKAY:AXI4_SLVERR, rid:rd_req.arid,rlast:(rd_req.arlen==0),rdata:data, ruser: ?};
			s_xactor.i_rd_data.enq(resp);
		endrule

		rule write_request(rg_wrburst_count==0);
			let addreq <- pop_o(s_xactor.o_wr_addr);
	        let datareq <- pop_o(s_xactor.o_wr_data);
	        rg_wrpacket<=addreq;
	        let succ <- sspi.mav_write_req(addreq.awaddr, datareq.wdata,unpack(truncate(addreq.awsize)));
	        if(addreq.awlen!=0)
	        	rg_wrburst_count<=1;
	        
	        let resp = AXI4_Wr_Resp {bresp: succ?AXI4_OKAY:AXI4_SLVERR, buser: ?, bid:addreq.awid};
	        if(datareq.wlast)
	        	s_xactor.i_wr_resp.enq(resp);
		endrule
		
		rule write_burst(rg_wrburst_count!=0);
			let addreq=rg_wrpacket;
	        let datareq <- pop_o(s_xactor.o_wr_data);
	 		Bool succ=False;
			let resp = AXI4_Wr_Resp {bresp: succ?AXI4_OKAY:AXI4_SLVERR, buser: ?, bid:addreq.awid};
			if(datareq.wlast)begin
	      		s_xactor.i_wr_resp.enq(resp);//enqueuing the write response
	      		rg_wrburst_count<=0;
	      	end
		endrule
		
		interface io = sspi.subifc_io;
		method sb_sspi_interrupt = sspi.mv_sb_sspi_interrupt;
		interface slave = s_xactor.axi_side;
	endmodule
/*	
(*synthesize*)
module mkdummy_axi4lite(Ifc_sspi_axi4lite#(64, 32, 0));
	let ifc();
  	mksspi_axi4lite _temp(ifc);
  return ifc;
endmodule

(*synthesize*)
module mkdummy_axi4(Ifc_sspi_axi4#(64, 32, 0));
	let ifc();
  	mksspi_axi4 _temp(ifc);
  return ifc;
endmodule
*/
endpackage
