############ DO NOT CHANGE THESE #################
SUPPORTED:=./../common_bsv:./../fabrics/axi4:./../fabrics/axi4lite:./../gpio_v2
TOP_MODULE?=mkdummy

############# User changes to be done below #################
TOP_DIR?= .
TOP_FILE?= gpio_template.bsv

