// Bluespec wrapper, created by Import BVI Wizard
// Created on: Wed Oct 10 12:05:12 IST 2018
// Created by: vishvesh
// Bluespec version: 2017.07.A 2017-07-21 1da80f1


interface Ifc_sdc_controller;
	(*always_ready*)
	method Action iwb_dat_i (Bit#(32) wb_dat_i);
	method Action icard_detect ();
	(*always_ready*)
	method Action iwb_adr_i (Bit#(8) wb_adr_i);
	(*always_ready*)
	method Action iwb_sel_i (Bit#(4) wb_sel_i);
	method Action iwb_we_i (bit wb_we_i);
	method Action iwb_cyc_i (bit wb_cyc_i);
	method Action iwb_stb_i (bit wb_stb_i );
	(*always_ready*)
	method Action im_wb_dat_i (Bit#(32) m_wb_dat_i);
	method Action im_wb_ack_i (bit m_wb_ack_i);
	(*always_ready*)
	method Action isd_dat_dat_i (Bit#(4) sd_dat_dat_i);
	method Action isd_cmd_dat_i (bit sd_cmd_dat_i);
	method Bit#(32) owb_dat_o ();
	method Bool owb_ack_o ();
	method Bit#(32) om_wb_adr_o ();
	method Bit#(4) om_wb_sel_o ();
	method Bool om_wb_we_o ();
	method Bit#(32) om_wb_dat_o ();
	method Bool om_wb_cyc_o ();
	method Bool om_wb_stb_o ();
	method Bit#(3) om_wb_cti_o ();
	method Bit#(2) om_wb_bte_o ();
	method Bit#(4) osd_dat_out_o ();
	method Bit#(1) osd_clk_o_pad ();
	method Bool oint_a ();
	method Bool oint_b ();
	method Bool oint_c ();
	method Bool osd_dat_oe_o ();
	method Bit#(1) osd_cmd_out_o ();
	method Bool osd_cmd_oe_o ();
endinterface

import "BVI" sdc_controller =
module mksdc_controller  (Ifc_sdc_controller);

	default_clock clk_wb_clk_i;
	default_reset rst_wb_rst_i;

	input_clock clk_wb_clk_i (wb_clk_i)  <- exposeCurrentClock;
	input_reset rst_wb_rst_i (wb_rst_i) clocked_by(clk_wb_clk_i)  <- exposeCurrentReset;


	method iwb_dat_i (wb_dat_i /*31:0*/)
		 enable((*inhigh*)iwb_dat_i_enable) clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method icard_detect ()
		 enable(card_detect) clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method iwb_adr_i (wb_adr_i /*7:0*/)
		 enable((*inhigh*)iwb_adr_i_enable) clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method iwb_sel_i (wb_sel_i /*3:0*/)
		 enable((*inhigh*)iwb_sel_i_enable) clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method iwb_we_i (wb_we_i /*0:0*/)
		 enable((*inhigh*)iwb_we_i_enable) clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method iwb_cyc_i (wb_cyc_i /*0:0*/)
		 enable((*inhigh*)iwb_cyc_i_enable) clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method iwb_stb_i (wb_stb_i /*0:0*/)
		 enable((*inhigh*)iwb_stb_i_enable) clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method im_wb_dat_i (m_wb_dat_i /*31:0*/)
		 enable((*inhigh*)im_wb_dat_i_enable) clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method im_wb_ack_i (m_wb_ack_i)
		 enable((*inhigh*)im_wb_ack_i_enable) clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method isd_dat_dat_i (sd_dat_dat_i /*3:0*/)
		 enable((*inhigh*)isd_dat_dat_i_enable) clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method isd_cmd_dat_i (sd_cmd_dat_i)
		 enable((*inhigh*)isd_cmd_dat_i_enable) clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method wb_dat_o /* 31 : 0 */ owb_dat_o ()
		 clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method wb_ack_o owb_ack_o ()
		 clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method m_wb_adr_o /* 31 : 0 */ om_wb_adr_o ()
		 clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method m_wb_sel_o /* 3 : 0 */ om_wb_sel_o ()
		 clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method m_wb_we_o om_wb_we_o ()
		 clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method m_wb_dat_o /* 31 : 0 */ om_wb_dat_o ()
		 clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method m_wb_cyc_o om_wb_cyc_o ()
		 clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method m_wb_stb_o om_wb_stb_o ()
		 clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method m_wb_cti_o /* 2 : 0 */ om_wb_cti_o ()
		 clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method m_wb_bte_o /* 1 : 0 */ om_wb_bte_o ()
		 clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method sd_dat_out_o /* 3 : 0 */ osd_dat_out_o ()
		 clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method sd_clk_o_pad osd_clk_o_pad ()
		 clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method int_a oint_a ()
		 clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method int_b oint_b ()
		 clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method int_c oint_c ()
		 clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method sd_dat_oe_o osd_dat_oe_o ()
		 clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method sd_cmd_out_o osd_cmd_out_o ()
		 clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);
	method sd_cmd_oe_o osd_cmd_oe_o ()
		 clocked_by(clk_wb_clk_i) reset_by(rst_wb_rst_i);

	schedule iwb_dat_i C iwb_dat_i;
	schedule iwb_dat_i CF icard_detect;
	schedule iwb_dat_i CF iwb_adr_i;
	schedule iwb_dat_i CF iwb_sel_i;
	schedule iwb_dat_i CF iwb_we_i;
	schedule iwb_dat_i CF iwb_cyc_i;
	schedule iwb_dat_i CF iwb_stb_i;
	schedule iwb_dat_i CF im_wb_dat_i;
	schedule iwb_dat_i CF im_wb_ack_i;
	schedule iwb_dat_i CF isd_dat_dat_i;
	schedule iwb_dat_i CF isd_cmd_dat_i;
	schedule owb_dat_o CF iwb_dat_i;
	schedule owb_ack_o CF iwb_dat_i;
	schedule om_wb_adr_o CF iwb_dat_i;
	schedule om_wb_sel_o CF iwb_dat_i;
	schedule om_wb_we_o CF iwb_dat_i;
	schedule om_wb_dat_o CF iwb_dat_i;
	schedule om_wb_cyc_o CF iwb_dat_i;
	schedule om_wb_stb_o CF iwb_dat_i;
	schedule om_wb_cti_o CF iwb_dat_i;
	schedule om_wb_bte_o CF iwb_dat_i;
	schedule osd_dat_out_o CF iwb_dat_i;
	schedule osd_clk_o_pad CF iwb_dat_i;
	schedule oint_a CF iwb_dat_i;
	schedule oint_b CF iwb_dat_i;
	schedule oint_c CF iwb_dat_i;
	schedule osd_dat_oe_o CF iwb_dat_i;
	schedule osd_cmd_out_o CF iwb_dat_i;
	schedule osd_cmd_oe_o CF iwb_dat_i;
	schedule icard_detect C icard_detect;
	schedule icard_detect CF iwb_adr_i;
	schedule icard_detect CF iwb_sel_i;
	schedule icard_detect CF iwb_we_i;
	schedule icard_detect CF iwb_cyc_i;
	schedule icard_detect CF iwb_stb_i;
	schedule icard_detect CF im_wb_dat_i;
	schedule icard_detect CF im_wb_ack_i;
	schedule icard_detect CF isd_dat_dat_i;
	schedule icard_detect CF isd_cmd_dat_i;
	schedule owb_dat_o CF icard_detect;
	schedule owb_ack_o CF icard_detect;
	schedule om_wb_adr_o CF icard_detect;
	schedule om_wb_sel_o CF icard_detect;
	schedule om_wb_we_o CF icard_detect;
	schedule om_wb_dat_o CF icard_detect;
	schedule om_wb_cyc_o CF icard_detect;
	schedule om_wb_stb_o CF icard_detect;
	schedule om_wb_cti_o CF icard_detect;
	schedule om_wb_bte_o CF icard_detect;
	schedule osd_dat_out_o CF icard_detect;
	schedule osd_clk_o_pad CF icard_detect;
	schedule oint_a CF icard_detect;
	schedule oint_b CF icard_detect;
	schedule oint_c CF icard_detect;
	schedule osd_dat_oe_o CF icard_detect;
	schedule osd_cmd_out_o CF icard_detect;
	schedule osd_cmd_oe_o CF icard_detect;
	schedule iwb_adr_i C iwb_adr_i;
	schedule iwb_adr_i CF iwb_sel_i;
	schedule iwb_adr_i CF iwb_we_i;
	schedule iwb_adr_i CF iwb_cyc_i;
	schedule iwb_adr_i CF iwb_stb_i;
	schedule iwb_adr_i CF im_wb_dat_i;
	schedule iwb_adr_i CF im_wb_ack_i;
	schedule iwb_adr_i CF isd_dat_dat_i;
	schedule iwb_adr_i CF isd_cmd_dat_i;
	schedule owb_dat_o CF iwb_adr_i;
	schedule owb_ack_o CF iwb_adr_i;
	schedule om_wb_adr_o CF iwb_adr_i;
	schedule om_wb_sel_o CF iwb_adr_i;
	schedule om_wb_we_o CF iwb_adr_i;
	schedule om_wb_dat_o CF iwb_adr_i;
	schedule om_wb_cyc_o CF iwb_adr_i;
	schedule om_wb_stb_o CF iwb_adr_i;
	schedule om_wb_cti_o CF iwb_adr_i;
	schedule om_wb_bte_o CF iwb_adr_i;
	schedule osd_dat_out_o CF iwb_adr_i;
	schedule osd_clk_o_pad CF iwb_adr_i;
	schedule oint_a CF iwb_adr_i;
	schedule oint_b CF iwb_adr_i;
	schedule oint_c CF iwb_adr_i;
	schedule osd_dat_oe_o CF iwb_adr_i;
	schedule osd_cmd_out_o CF iwb_adr_i;
	schedule osd_cmd_oe_o CF iwb_adr_i;
	schedule iwb_sel_i C iwb_sel_i;
	schedule iwb_sel_i CF iwb_we_i;
	schedule iwb_sel_i CF iwb_cyc_i;
	schedule iwb_sel_i CF iwb_stb_i;
	schedule iwb_sel_i CF im_wb_dat_i;
	schedule iwb_sel_i CF im_wb_ack_i;
	schedule iwb_sel_i CF isd_dat_dat_i;
	schedule iwb_sel_i CF isd_cmd_dat_i;
	schedule owb_dat_o CF iwb_sel_i;
	schedule owb_ack_o CF iwb_sel_i;
	schedule om_wb_adr_o CF iwb_sel_i;
	schedule om_wb_sel_o CF iwb_sel_i;
	schedule om_wb_we_o CF iwb_sel_i;
	schedule om_wb_dat_o CF iwb_sel_i;
	schedule om_wb_cyc_o CF iwb_sel_i;
	schedule om_wb_stb_o CF iwb_sel_i;
	schedule om_wb_cti_o CF iwb_sel_i;
	schedule om_wb_bte_o CF iwb_sel_i;
	schedule osd_dat_out_o CF iwb_sel_i;
	schedule osd_clk_o_pad CF iwb_sel_i;
	schedule oint_a CF iwb_sel_i;
	schedule oint_b CF iwb_sel_i;
	schedule oint_c CF iwb_sel_i;
	schedule osd_dat_oe_o CF iwb_sel_i;
	schedule osd_cmd_out_o CF iwb_sel_i;
	schedule osd_cmd_oe_o CF iwb_sel_i;
	schedule iwb_we_i C iwb_we_i;
	schedule iwb_we_i CF iwb_cyc_i;
	schedule iwb_we_i CF iwb_stb_i;
	schedule iwb_we_i CF im_wb_dat_i;
	schedule iwb_we_i CF im_wb_ack_i;
	schedule iwb_we_i CF isd_dat_dat_i;
	schedule iwb_we_i CF isd_cmd_dat_i;
	schedule owb_dat_o CF iwb_we_i;
	schedule owb_ack_o CF iwb_we_i;
	schedule om_wb_adr_o CF iwb_we_i;
	schedule om_wb_sel_o CF iwb_we_i;
	schedule om_wb_we_o CF iwb_we_i;
	schedule om_wb_dat_o CF iwb_we_i;
	schedule om_wb_cyc_o CF iwb_we_i;
	schedule om_wb_stb_o CF iwb_we_i;
	schedule om_wb_cti_o CF iwb_we_i;
	schedule om_wb_bte_o CF iwb_we_i;
	schedule osd_dat_out_o CF iwb_we_i;
	schedule osd_clk_o_pad CF iwb_we_i;
	schedule oint_a CF iwb_we_i;
	schedule oint_b CF iwb_we_i;
	schedule oint_c CF iwb_we_i;
	schedule osd_dat_oe_o CF iwb_we_i;
	schedule osd_cmd_out_o CF iwb_we_i;
	schedule osd_cmd_oe_o CF iwb_we_i;
	schedule iwb_cyc_i C iwb_cyc_i;
	schedule iwb_cyc_i CF iwb_stb_i;
	schedule iwb_cyc_i CF im_wb_dat_i;
	schedule iwb_cyc_i CF im_wb_ack_i;
	schedule iwb_cyc_i CF isd_dat_dat_i;
	schedule iwb_cyc_i CF isd_cmd_dat_i;
	schedule owb_dat_o CF iwb_cyc_i;
	schedule owb_ack_o CF iwb_cyc_i;
	schedule om_wb_adr_o CF iwb_cyc_i;
	schedule om_wb_sel_o CF iwb_cyc_i;
	schedule om_wb_we_o CF iwb_cyc_i;
	schedule om_wb_dat_o CF iwb_cyc_i;
	schedule om_wb_cyc_o CF iwb_cyc_i;
	schedule om_wb_stb_o CF iwb_cyc_i;
	schedule om_wb_cti_o CF iwb_cyc_i;
	schedule om_wb_bte_o CF iwb_cyc_i;
	schedule osd_dat_out_o CF iwb_cyc_i;
	schedule osd_clk_o_pad CF iwb_cyc_i;
	schedule oint_a CF iwb_cyc_i;
	schedule oint_b CF iwb_cyc_i;
	schedule oint_c CF iwb_cyc_i;
	schedule osd_dat_oe_o CF iwb_cyc_i;
	schedule osd_cmd_out_o CF iwb_cyc_i;
	schedule osd_cmd_oe_o CF iwb_cyc_i;
	schedule iwb_stb_i C iwb_stb_i;
	schedule iwb_stb_i CF im_wb_dat_i;
	schedule iwb_stb_i CF im_wb_ack_i;
	schedule iwb_stb_i CF isd_dat_dat_i;
	schedule iwb_stb_i CF isd_cmd_dat_i;
	schedule owb_dat_o CF iwb_stb_i;
	schedule owb_ack_o CF iwb_stb_i;
	schedule om_wb_adr_o CF iwb_stb_i;
	schedule om_wb_sel_o CF iwb_stb_i;
	schedule om_wb_we_o CF iwb_stb_i;
	schedule om_wb_dat_o CF iwb_stb_i;
	schedule om_wb_cyc_o CF iwb_stb_i;
	schedule om_wb_stb_o CF iwb_stb_i;
	schedule om_wb_cti_o CF iwb_stb_i;
	schedule om_wb_bte_o CF iwb_stb_i;
	schedule osd_dat_out_o CF iwb_stb_i;
	schedule osd_clk_o_pad CF iwb_stb_i;
	schedule oint_a CF iwb_stb_i;
	schedule oint_b CF iwb_stb_i;
	schedule oint_c CF iwb_stb_i;
	schedule osd_dat_oe_o CF iwb_stb_i;
	schedule osd_cmd_out_o CF iwb_stb_i;
	schedule osd_cmd_oe_o CF iwb_stb_i;
	schedule im_wb_dat_i C im_wb_dat_i;
	schedule im_wb_dat_i CF im_wb_ack_i;
	schedule im_wb_dat_i CF isd_dat_dat_i;
	schedule im_wb_dat_i CF isd_cmd_dat_i;
	schedule owb_dat_o CF im_wb_dat_i;
	schedule owb_ack_o CF im_wb_dat_i;
	schedule om_wb_adr_o CF im_wb_dat_i;
	schedule om_wb_sel_o CF im_wb_dat_i;
	schedule om_wb_we_o CF im_wb_dat_i;
	schedule om_wb_dat_o CF im_wb_dat_i;
	schedule om_wb_cyc_o CF im_wb_dat_i;
	schedule om_wb_stb_o CF im_wb_dat_i;
	schedule om_wb_cti_o CF im_wb_dat_i;
	schedule om_wb_bte_o CF im_wb_dat_i;
	schedule osd_dat_out_o CF im_wb_dat_i;
	schedule osd_clk_o_pad CF im_wb_dat_i;
	schedule oint_a CF im_wb_dat_i;
	schedule oint_b CF im_wb_dat_i;
	schedule oint_c CF im_wb_dat_i;
	schedule osd_dat_oe_o CF im_wb_dat_i;
	schedule osd_cmd_out_o CF im_wb_dat_i;
	schedule osd_cmd_oe_o CF im_wb_dat_i;
	schedule im_wb_ack_i C im_wb_ack_i;
	schedule im_wb_ack_i CF isd_dat_dat_i;
	schedule im_wb_ack_i CF isd_cmd_dat_i;
	schedule owb_dat_o CF im_wb_ack_i;
	schedule owb_ack_o CF im_wb_ack_i;
	schedule om_wb_adr_o CF im_wb_ack_i;
	schedule om_wb_sel_o CF im_wb_ack_i;
	schedule om_wb_we_o CF im_wb_ack_i;
	schedule om_wb_dat_o CF im_wb_ack_i;
	schedule om_wb_cyc_o CF im_wb_ack_i;
	schedule om_wb_stb_o CF im_wb_ack_i;
	schedule om_wb_cti_o CF im_wb_ack_i;
	schedule om_wb_bte_o CF im_wb_ack_i;
	schedule osd_dat_out_o CF im_wb_ack_i;
	schedule osd_clk_o_pad CF im_wb_ack_i;
	schedule oint_a CF im_wb_ack_i;
	schedule oint_b CF im_wb_ack_i;
	schedule oint_c CF im_wb_ack_i;
	schedule osd_dat_oe_o CF im_wb_ack_i;
	schedule osd_cmd_out_o CF im_wb_ack_i;
	schedule osd_cmd_oe_o CF im_wb_ack_i;
	schedule isd_dat_dat_i C isd_dat_dat_i;
	schedule isd_dat_dat_i CF isd_cmd_dat_i;
	schedule owb_dat_o CF isd_dat_dat_i;
	schedule owb_ack_o CF isd_dat_dat_i;
	schedule om_wb_adr_o CF isd_dat_dat_i;
	schedule om_wb_sel_o CF isd_dat_dat_i;
	schedule om_wb_we_o CF isd_dat_dat_i;
	schedule om_wb_dat_o CF isd_dat_dat_i;
	schedule om_wb_cyc_o CF isd_dat_dat_i;
	schedule om_wb_stb_o CF isd_dat_dat_i;
	schedule om_wb_cti_o CF isd_dat_dat_i;
	schedule om_wb_bte_o CF isd_dat_dat_i;
	schedule osd_dat_out_o CF isd_dat_dat_i;
	schedule osd_clk_o_pad CF isd_dat_dat_i;
	schedule oint_a CF isd_dat_dat_i;
	schedule oint_b CF isd_dat_dat_i;
	schedule oint_c CF isd_dat_dat_i;
	schedule osd_dat_oe_o CF isd_dat_dat_i;
	schedule osd_cmd_out_o CF isd_dat_dat_i;
	schedule osd_cmd_oe_o CF isd_dat_dat_i;
	schedule isd_cmd_dat_i C isd_cmd_dat_i;
	schedule owb_dat_o CF isd_cmd_dat_i;
	schedule owb_ack_o CF isd_cmd_dat_i;
	schedule om_wb_adr_o CF isd_cmd_dat_i;
	schedule om_wb_sel_o CF isd_cmd_dat_i;
	schedule om_wb_we_o CF isd_cmd_dat_i;
	schedule om_wb_dat_o CF isd_cmd_dat_i;
	schedule om_wb_cyc_o CF isd_cmd_dat_i;
	schedule om_wb_stb_o CF isd_cmd_dat_i;
	schedule om_wb_cti_o CF isd_cmd_dat_i;
	schedule om_wb_bte_o CF isd_cmd_dat_i;
	schedule osd_dat_out_o CF isd_cmd_dat_i;
	schedule osd_clk_o_pad CF isd_cmd_dat_i;
	schedule oint_a CF isd_cmd_dat_i;
	schedule oint_b CF isd_cmd_dat_i;
	schedule oint_c CF isd_cmd_dat_i;
	schedule osd_dat_oe_o CF isd_cmd_dat_i;
	schedule osd_cmd_out_o CF isd_cmd_dat_i;
	schedule osd_cmd_oe_o CF isd_cmd_dat_i;
	schedule owb_dat_o CF owb_dat_o;
	schedule owb_dat_o CF owb_ack_o;
	schedule owb_dat_o CF om_wb_adr_o;
	schedule owb_dat_o CF om_wb_sel_o;
	schedule owb_dat_o CF om_wb_we_o;
	schedule owb_dat_o CF om_wb_dat_o;
	schedule owb_dat_o CF om_wb_cyc_o;
	schedule owb_dat_o CF om_wb_stb_o;
	schedule owb_dat_o CF om_wb_cti_o;
	schedule owb_dat_o CF om_wb_bte_o;
	schedule owb_dat_o CF osd_dat_out_o;
	schedule owb_dat_o CF osd_clk_o_pad;
	schedule owb_dat_o CF oint_a;
	schedule owb_dat_o CF oint_b;
	schedule owb_dat_o CF oint_c;
	schedule owb_dat_o CF osd_dat_oe_o;
	schedule owb_dat_o CF osd_cmd_out_o;
	schedule owb_dat_o CF osd_cmd_oe_o;
	schedule owb_ack_o CF owb_ack_o;
	schedule owb_ack_o CF om_wb_adr_o;
	schedule owb_ack_o CF om_wb_sel_o;
	schedule owb_ack_o CF om_wb_we_o;
	schedule owb_ack_o CF om_wb_dat_o;
	schedule owb_ack_o CF om_wb_cyc_o;
	schedule owb_ack_o CF om_wb_stb_o;
	schedule owb_ack_o CF om_wb_cti_o;
	schedule owb_ack_o CF om_wb_bte_o;
	schedule owb_ack_o CF osd_dat_out_o;
	schedule owb_ack_o CF osd_clk_o_pad;
	schedule owb_ack_o CF oint_a;
	schedule owb_ack_o CF oint_b;
	schedule owb_ack_o CF oint_c;
	schedule owb_ack_o CF osd_dat_oe_o;
	schedule owb_ack_o CF osd_cmd_out_o;
	schedule owb_ack_o CF osd_cmd_oe_o;
	schedule om_wb_adr_o CF om_wb_adr_o;
	schedule om_wb_adr_o CF om_wb_sel_o;
	schedule om_wb_adr_o CF om_wb_we_o;
	schedule om_wb_adr_o CF om_wb_dat_o;
	schedule om_wb_adr_o CF om_wb_cyc_o;
	schedule om_wb_adr_o CF om_wb_stb_o;
	schedule om_wb_adr_o CF om_wb_cti_o;
	schedule om_wb_adr_o CF om_wb_bte_o;
	schedule om_wb_adr_o CF osd_dat_out_o;
	schedule om_wb_adr_o CF osd_clk_o_pad;
	schedule om_wb_adr_o CF oint_a;
	schedule om_wb_adr_o CF oint_b;
	schedule om_wb_adr_o CF oint_c;
	schedule om_wb_adr_o CF osd_dat_oe_o;
	schedule om_wb_adr_o CF osd_cmd_out_o;
	schedule om_wb_adr_o CF osd_cmd_oe_o;
	schedule om_wb_sel_o CF om_wb_sel_o;
	schedule om_wb_sel_o CF om_wb_we_o;
	schedule om_wb_sel_o CF om_wb_dat_o;
	schedule om_wb_sel_o CF om_wb_cyc_o;
	schedule om_wb_sel_o CF om_wb_stb_o;
	schedule om_wb_sel_o CF om_wb_cti_o;
	schedule om_wb_sel_o CF om_wb_bte_o;
	schedule om_wb_sel_o CF osd_dat_out_o;
	schedule om_wb_sel_o CF osd_clk_o_pad;
	schedule om_wb_sel_o CF oint_a;
	schedule om_wb_sel_o CF oint_b;
	schedule om_wb_sel_o CF oint_c;
	schedule om_wb_sel_o CF osd_dat_oe_o;
	schedule om_wb_sel_o CF osd_cmd_out_o;
	schedule om_wb_sel_o CF osd_cmd_oe_o;
	schedule om_wb_we_o CF om_wb_we_o;
	schedule om_wb_we_o CF om_wb_dat_o;
	schedule om_wb_we_o CF om_wb_cyc_o;
	schedule om_wb_we_o CF om_wb_stb_o;
	schedule om_wb_we_o CF om_wb_cti_o;
	schedule om_wb_we_o CF om_wb_bte_o;
	schedule om_wb_we_o CF osd_dat_out_o;
	schedule om_wb_we_o CF osd_clk_o_pad;
	schedule om_wb_we_o CF oint_a;
	schedule om_wb_we_o CF oint_b;
	schedule om_wb_we_o CF oint_c;
	schedule om_wb_we_o CF osd_dat_oe_o;
	schedule om_wb_we_o CF osd_cmd_out_o;
	schedule om_wb_we_o CF osd_cmd_oe_o;
	schedule om_wb_dat_o CF om_wb_dat_o;
	schedule om_wb_dat_o CF om_wb_cyc_o;
	schedule om_wb_dat_o CF om_wb_stb_o;
	schedule om_wb_dat_o CF om_wb_cti_o;
	schedule om_wb_dat_o CF om_wb_bte_o;
	schedule om_wb_dat_o CF osd_dat_out_o;
	schedule om_wb_dat_o CF osd_clk_o_pad;
	schedule om_wb_dat_o CF oint_a;
	schedule om_wb_dat_o CF oint_b;
	schedule om_wb_dat_o CF oint_c;
	schedule om_wb_dat_o CF osd_dat_oe_o;
	schedule om_wb_dat_o CF osd_cmd_out_o;
	schedule om_wb_dat_o CF osd_cmd_oe_o;
	schedule om_wb_cyc_o CF om_wb_cyc_o;
	schedule om_wb_cyc_o CF om_wb_stb_o;
	schedule om_wb_cyc_o CF om_wb_cti_o;
	schedule om_wb_cyc_o CF om_wb_bte_o;
	schedule om_wb_cyc_o CF osd_dat_out_o;
	schedule om_wb_cyc_o CF osd_clk_o_pad;
	schedule om_wb_cyc_o CF oint_a;
	schedule om_wb_cyc_o CF oint_b;
	schedule om_wb_cyc_o CF oint_c;
	schedule om_wb_cyc_o CF osd_dat_oe_o;
	schedule om_wb_cyc_o CF osd_cmd_out_o;
	schedule om_wb_cyc_o CF osd_cmd_oe_o;
	schedule om_wb_stb_o CF om_wb_stb_o;
	schedule om_wb_stb_o CF om_wb_cti_o;
	schedule om_wb_stb_o CF om_wb_bte_o;
	schedule om_wb_stb_o CF osd_dat_out_o;
	schedule om_wb_stb_o CF osd_clk_o_pad;
	schedule om_wb_stb_o CF oint_a;
	schedule om_wb_stb_o CF oint_b;
	schedule om_wb_stb_o CF oint_c;
	schedule om_wb_stb_o CF osd_dat_oe_o;
	schedule om_wb_stb_o CF osd_cmd_out_o;
	schedule om_wb_stb_o CF osd_cmd_oe_o;
	schedule om_wb_cti_o CF om_wb_cti_o;
	schedule om_wb_cti_o CF om_wb_bte_o;
	schedule om_wb_cti_o CF osd_dat_out_o;
	schedule om_wb_cti_o CF osd_clk_o_pad;
	schedule om_wb_cti_o CF oint_a;
	schedule om_wb_cti_o CF oint_b;
	schedule om_wb_cti_o CF oint_c;
	schedule om_wb_cti_o CF osd_dat_oe_o;
	schedule om_wb_cti_o CF osd_cmd_out_o;
	schedule om_wb_cti_o CF osd_cmd_oe_o;
	schedule om_wb_bte_o CF om_wb_bte_o;
	schedule om_wb_bte_o CF osd_dat_out_o;
	schedule om_wb_bte_o CF osd_clk_o_pad;
	schedule om_wb_bte_o CF oint_a;
	schedule om_wb_bte_o CF oint_b;
	schedule om_wb_bte_o CF oint_c;
	schedule om_wb_bte_o CF osd_dat_oe_o;
	schedule om_wb_bte_o CF osd_cmd_out_o;
	schedule om_wb_bte_o CF osd_cmd_oe_o;
	schedule osd_dat_out_o CF osd_dat_out_o;
	schedule osd_dat_out_o CF osd_clk_o_pad;
	schedule osd_dat_out_o CF oint_a;
	schedule osd_dat_out_o CF oint_b;
	schedule osd_dat_out_o CF oint_c;
	schedule osd_dat_out_o CF osd_dat_oe_o;
	schedule osd_dat_out_o CF osd_cmd_out_o;
	schedule osd_dat_out_o CF osd_cmd_oe_o;
	schedule osd_clk_o_pad CF osd_clk_o_pad;
	schedule osd_clk_o_pad CF oint_a;
	schedule osd_clk_o_pad CF oint_b;
	schedule osd_clk_o_pad CF oint_c;
	schedule osd_clk_o_pad CF osd_dat_oe_o;
	schedule osd_clk_o_pad CF osd_cmd_out_o;
	schedule osd_clk_o_pad CF osd_cmd_oe_o;
	schedule oint_a CF oint_a;
	schedule oint_a CF oint_b;
	schedule oint_a CF oint_c;
	schedule oint_a CF osd_dat_oe_o;
	schedule oint_a CF osd_cmd_out_o;
	schedule oint_a CF osd_cmd_oe_o;
	schedule oint_b CF oint_b;
	schedule oint_b CF oint_c;
	schedule oint_b CF osd_dat_oe_o;
	schedule oint_b CF osd_cmd_out_o;
	schedule oint_b CF osd_cmd_oe_o;
	schedule oint_c CF oint_c;
	schedule oint_c CF osd_dat_oe_o;
	schedule oint_c CF osd_cmd_out_o;
	schedule oint_c CF osd_cmd_oe_o;
	schedule osd_dat_oe_o CF osd_dat_oe_o;
	schedule osd_dat_oe_o CF osd_cmd_out_o;
	schedule osd_dat_oe_o CF osd_cmd_oe_o;
	schedule osd_cmd_out_o CF osd_cmd_out_o;
	schedule osd_cmd_out_o CF osd_cmd_oe_o;
	schedule osd_cmd_oe_o CF osd_cmd_oe_o;
endmodule


